#COMMON BEGINING

In [65]:
!pip install pandas_market_calendars
!pip install mysql.connector

Requirement already satisfied: pandas_market_calendars in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (4.3.3)
Requirement already satisfied: pandas<2.0,>=1.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from pandas_market_calendars) (1.5.3)
Requirement already satisfied: pytz in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from pandas_market_calendars) (2023.3)
Requirement already satisfied: python-dateutil in /Users/vinayak/Library/Python/3.11/lib/python/site-packages (from pandas_market_calendars) (2.8.2)
Requirement already satisfied: exchange-calendars>=3.3 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from pandas_market_calendars) (4.5.1)
Requirement already satisfied: numpy in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from exchange-calendars>=3.3->pandas_market_calendars) (1.24.3)
Requirement already satisfied: pyluach in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from exchange-calendars>=3.3->pandas_market_calendars) (2.2.0)
Requirement already satisfied: toolz in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from exchange-calendars>=3.3->pandas_market_calendars) (0.12.0)
Requirement already satisfied: tzdata in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from exchange-calendars>=3.3->pandas_market_calendars) (2023.3)
Requirement already satisfied: korean-lunar-calendar in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from exchange-calendars>=3.3->pandas_market_calendars) (0.3.1)
Requirement already satisfied: six>=1.5 in /Users/vinayak/Library/Python/3.11/lib/python/site-packages (from python-dateutil->pandas_market_calendars) (1.16.0)
^C
ERROR: Operation cancelled by user

In [ ]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta
import pandas_market_calendars as mcal
import requests

In [ ]:
import pandas as pd
import mysql.connector
from datetime import datetime, timedelta

# Database connection details
host = "182.18.139.134"
user = "IITR"
password = "iitr@2023"
database = "admin_mmalpha"

# Establish database connection
conn = mysql.connector.connect(host=host, user=user, password=password, database=database)
cursor = conn.cursor()

table_name = "sr_his_eqs"
# Set end_date as today's date
end_date = datetime.today().strftime('%Y-%m-%d')
working_days_limit = 252 * 2556

# Modify the query to get data for the last 252 working days
query = f"""
    SELECT *
    FROM {table_name}
    WHERE   st_date <= '{end_date}'
    ORDER BY st_date DESC
    LIMIT {working_days_limit};
"""

try:
    # Execute the query
    cursor.execute(query)

    # Fetch all rows from the result set
    rows = cursor.fetchall()

    # Get column names
    column_names = [desc[0] for desc in cursor.description]

    # Create a DataFrame from the fetched data
    df = pd.DataFrame(rows, columns=column_names)

    # Display the DataFrame
    print(df)

except mysql.connector.Error as err:
    print("Error:", err)

# Close the cursor and connection
cursor.close()
conn.close()

         st_symbol st_series  st_open  st_high   st_low  st_close  st_last  \
0              KEC        EQ   624.60   626.50   614.20    625.05   624.05
1             KECL        EQ   122.55   123.65   120.55    121.00   121.20
2        KEEPLEARN        BE     6.25     6.30     6.00      6.30     6.30
3              KEI        EQ  3147.00  3159.00  3026.95   3112.85  3124.00
4              KEL        SM   226.00   236.00   222.15    236.00   236.00
...            ...       ...      ...      ...      ...       ...      ...
644107   TGBHOTELS        EQ    13.30    13.55    12.80     13.00    12.95
644108  THANGAMAYL        EQ  1099.95  1110.50  1070.05   1107.80  1110.00
644109   THEINVEST        EQ    86.55    89.50    85.45     88.30    88.20
644110   THEMISMED        EQ  1380.00  1410.00  1355.00   1396.25  1406.00
644111     THERMAX        EQ  1978.00  1978.00  1940.00   1961.30  1960.15

        st_pclose  st_trd_qty  st_trd_value     st_date  st_totaltrades  \
0          621.50    246701.0  1.535553e+08  2024-01-19         18048.0
1          121.70    292886.0  3.575023e+07  2024-01-19          4493.0
2            6.00    261723.0  1.644946e+06  2024-01-19           116.0
3         3140.40    369313.0  1.156578e+09  2024-01-19         12410.0
4          227.00     10800.0  2.476380e+06  2024-01-19             8.0
...           ...         ...           ...         ...             ...
644107      12.95    128823.0  1.687251e+06  2023-01-02           348.0
644108    1094.45      7169.0  7.911417e+06  2023-01-02          1011.0
644109      86.60     19826.0  1.723880e+06  2023-01-02           141.0
644110    1354.95     22621.0  3.121794e+07  2023-01-02          5334.0
644111    1968.20     23445.0  4.594200e+07  2023-01-02          3432.0

             st_isin
0       INE389H01022
1       INE134B01017
2       INE055C01020
3       INE878B01027
4       INE0OWX01025
...              ...
644107  INE797H01018
644108  INE085J01014
644109  INE924D01017
644110  INE083B01016
644111  INE152A01029

[644112 rows x 13 columns]

In [ ]:
df

,st_symbol,st_series,st_open,st_high,st_low,st_close,st_last,st_pclose,st_trd_qty,st_trd_value,st_date,st_totaltrades,st_isin
0,KEC,EQ,624.60,626.50,614.20,625.05,624.05,621.50,246701.0,1.535553e+08,2024-01-19,18048.0,INE389H01022
1,KECL,EQ,122.55,123.65,120.55,121.00,121.20,121.70,292886.0,3.575023e+07,2024-01-19,4493.0,INE134B01017
2,KEEPLEARN,BE,6.25,6.30,6.00,6.30,6.30,6.00,261723.0,1.644946e+06,2024-01-19,116.0,INE055C01020
3,KEI,EQ,3147.00,3159.00,3026.95,3112.85,3124.00,3140.40,369313.0,1.156578e+09,2024-01-19,12410.0,INE878B01027
4,KEL,SM,226.00,236.00,222.15,236.00,236.00,227.00,10800.0,2.476380e+06,2024-01-19,8.0,INE0OWX01025
...,...,...,...,...,...,...,...,...,...,...,...,...,...
644107,TGBHOTELS,EQ,13.30,13.55,12.80,13.00,12.95,12.95,128823.0,1.687251e+06,2023-01-02,348.0,INE797H01018
644108,THANGAMAYL,EQ,1099.95,1110.50,1070.05,1107.80,1110.00,1094.45,7169.0,7.911417e+06,2023-01-02,1011.0,INE085J01014
644109,THEINVEST,EQ,86.55,89.50,85.45,88.30,88.20,86.60,19826.0,1.723880e+06,2023-01-02,141.0,INE924D01017
644110,THEMISMED,EQ,1380.00,1410.00,1355.00,1396.25,1406.00,1354.95,22621.0,3.121794e+07,2023-01-02,5334.0,INE083B01016
644111,THERMAX,EQ,1978.00,1978.00,1940.00,1961.30,1960.15,1968.20,23445.0,4.594200e+07,2023-01-02,3432.0,INE152A01029

In [ ]:
import pandas as pd

# # Assuming df is your DataFrame
# df = pd.DataFrame(df, columns=['st_symbol', 'st_series', 'st_open', 'st_high', 'st_low', 'st_close',
#                                        'st_last', 'st_pclose', 'st_trd_qty', 'st_trd_value', 'st_date',
#                                        'st_totaltrades', 'BODY'])

# Define the new column names
new_column_names = {'st_symbol': 'SYMBOL',
                    'st_series': ' SERIES',
                    'st_open': ' OPEN_PRICE',
                    'st_high': ' HIGH_PRICE',
                    'st_low': ' LOW_PRICE',
                    'st_close': ' CLOSE_PRICE',
                    'st_last': ' LAST_PRICE',
                    'st_pclose': ' PREV_CLOSE',
                    'st_trd_qty': ' TTL_TRD_QNTY',
                    'st_trd_value': 'TRD_VALUE',
                    'st_date': ' DATE1',
                    'st_totaltrades': 'TOTAL_TRADES',
                    'BODY': 'BODY'}

# Rename the columns
df.rename(columns=new_column_names, inplace=True)

# Display the DataFrame with the renamed columns
print(df)

            SYMBOL  SERIES   OPEN_PRICE   HIGH_PRICE   LOW_PRICE  \
0              KEC      EQ       624.60       626.50      614.20
1             KECL      EQ       122.55       123.65      120.55
2        KEEPLEARN      BE         6.25         6.30        6.00
3              KEI      EQ      3147.00      3159.00     3026.95
4              KEL      SM       226.00       236.00      222.15
...            ...     ...          ...          ...         ...
644107   TGBHOTELS      EQ        13.30        13.55       12.80
644108  THANGAMAYL      EQ      1099.95      1110.50     1070.05
644109   THEINVEST      EQ        86.55        89.50       85.45
644110   THEMISMED      EQ      1380.00      1410.00     1355.00
644111     THERMAX      EQ      1978.00      1978.00     1940.00

         CLOSE_PRICE   LAST_PRICE   PREV_CLOSE   TTL_TRD_QNTY     TRD_VALUE  \
0             625.05       624.05       621.50       246701.0  1.535553e+08
1             121.00       121.20       121.70       292886.0  3.575023e+07
2               6.30         6.30         6.00       261723.0  1.644946e+06
3            3112.85      3124.00      3140.40       369313.0  1.156578e+09
4             236.00       236.00       227.00        10800.0  2.476380e+06
...              ...          ...          ...            ...           ...
644107         13.00        12.95        12.95       128823.0  1.687251e+06
644108       1107.80      1110.00      1094.45         7169.0  7.911417e+06
644109         88.30        88.20        86.60        19826.0  1.723880e+06
644110       1396.25      1406.00      1354.95        22621.0  3.121794e+07
644111       1961.30      1960.15      1968.20        23445.0  4.594200e+07

             DATE1  TOTAL_TRADES       st_isin
0       2024-01-19       18048.0  INE389H01022
1       2024-01-19        4493.0  INE134B01017
2       2024-01-19         116.0  INE055C01020
3       2024-01-19       12410.0  INE878B01027
4       2024-01-19           8.0  INE0OWX01025
...            ...           ...           ...
644107  2023-01-02         348.0  INE797H01018
644108  2023-01-02        1011.0  INE085J01014
644109  2023-01-02         141.0  INE924D01017
644110  2023-01-02        5334.0  INE083B01016
644111  2023-01-02        3432.0  INE152A01029

[644112 rows x 13 columns]

In [ ]:
df.columns

Index(['SYMBOL', ' SERIES', ' OPEN_PRICE', ' HIGH_PRICE', ' LOW_PRICE',
       ' CLOSE_PRICE', ' LAST_PRICE', ' PREV_CLOSE', ' TTL_TRD_QNTY',
       'TRD_VALUE', ' DATE1', 'TOTAL_TRADES', 'st_isin'],
      dtype='object')

In [ ]:
df2=df.copy()

In [ ]:
df.drop(columns=['st_isin'], inplace=True)

In [ ]:
df['BODY'] = (df[' CLOSE_PRICE']-df[' OPEN_PRICE'])

In [ ]:
df['color'] = 'red'  # Initialize all rows to 'red'
df.loc[df[' OPEN_PRICE'] <= df[' CLOSE_PRICE'], 'color'] = 'green'

In [ ]:
combined_df= df.copy()
combined_df = combined_df[combined_df[' SERIES'].isin(['EQ', 'BE'])]

In [ ]:
combined_df.to_csv('cf',index=False)

In [ ]:
print(combined_df[' DATE1'].unique())

[datetime.date(2024, 1, 19) datetime.date(2024, 1, 18)
 datetime.date(2024, 1, 17) datetime.date(2024, 1, 16)
 datetime.date(2024, 1, 15) datetime.date(2024, 1, 12)
 datetime.date(2024, 1, 11) datetime.date(2024, 1, 10)
 datetime.date(2024, 1, 9) datetime.date(2024, 1, 8)
 datetime.date(2024, 1, 5) datetime.date(2024, 1, 4)
 datetime.date(2024, 1, 3) datetime.date(2024, 1, 2)
 datetime.date(2024, 1, 1) datetime.date(2023, 12, 29)
 datetime.date(2023, 12, 28) datetime.date(2023, 12, 27)
 datetime.date(2023, 12, 26) datetime.date(2023, 12, 22)
 datetime.date(2023, 12, 21) datetime.date(2023, 12, 20)
 datetime.date(2023, 12, 19) datetime.date(2023, 12, 18)
 datetime.date(2023, 12, 15) datetime.date(2023, 12, 14)
 datetime.date(2023, 12, 13) datetime.date(2023, 12, 12)
 datetime.date(2023, 12, 11) datetime.date(2023, 12, 8)
 datetime.date(2023, 12, 7) datetime.date(2023, 12, 6)
 datetime.date(2023, 12, 5) datetime.date(2023, 12, 4)
 datetime.date(2023, 12, 1) datetime.date(2023, 11, 30)
 datetime.date(2023, 11, 29) datetime.date(2023, 11, 28)
 datetime.date(2023, 11, 24) datetime.date(2023, 11, 23)
 datetime.date(2023, 11, 22) datetime.date(2023, 11, 21)
 datetime.date(2023, 11, 20) datetime.date(2023, 11, 17)
 datetime.date(2023, 11, 16) datetime.date(2023, 11, 15)
 datetime.date(2023, 11, 13) datetime.date(2023, 11, 12)
 datetime.date(2023, 11, 10) datetime.date(2023, 11, 9)
 datetime.date(2023, 11, 8) datetime.date(2023, 11, 7)
 datetime.date(2023, 11, 6) datetime.date(2023, 11, 3)
 datetime.date(2023, 11, 2) datetime.date(2023, 11, 1)
 datetime.date(2023, 10, 31) datetime.date(2023, 10, 30)
 datetime.date(2023, 10, 27) datetime.date(2023, 10, 26)
 datetime.date(2023, 10, 25) datetime.date(2023, 10, 23)
 datetime.date(2023, 10, 20) datetime.date(2023, 10, 19)
 datetime.date(2023, 10, 18) datetime.date(2023, 10, 17)
 datetime.date(2023, 10, 16) datetime.date(2023, 10, 13)
 datetime.date(2023, 10, 12) datetime.date(2023, 10, 11)
 datetime.date(2023, 10, 10) datetime.date(2023, 10, 9)
 datetime.date(2023, 10, 6) datetime.date(2023, 10, 5)
 datetime.date(2023, 10, 4) datetime.date(2023, 10, 3)
 datetime.date(2023, 9, 29) datetime.date(2023, 9, 28)
 datetime.date(2023, 9, 27) datetime.date(2023, 9, 26)
 datetime.date(2023, 9, 25) datetime.date(2023, 9, 22)
 datetime.date(2023, 9, 21) datetime.date(2023, 9, 20)
 datetime.date(2023, 9, 18) datetime.date(2023, 9, 15)
 datetime.date(2023, 9, 14) datetime.date(2023, 9, 13)
 datetime.date(2023, 9, 12) datetime.date(2023, 9, 11)
 datetime.date(2023, 9, 8) datetime.date(2023, 9, 7)
 datetime.date(2023, 9, 6) datetime.date(2023, 9, 5)
 datetime.date(2023, 9, 4) datetime.date(2023, 9, 1)
 datetime.date(2023, 8, 31) datetime.date(2023, 8, 30)
 datetime.date(2023, 8, 29) datetime.date(2023, 8, 28)
 datetime.date(2023, 8, 25) datetime.date(2023, 8, 24)
 datetime.date(2023, 8, 23) datetime.date(2023, 8, 22)
 datetime.date(2023, 8, 21) datetime.date(2023, 8, 18)
 datetime.date(2023, 8, 17) datetime.date(2023, 8, 16)
 datetime.date(2023, 8, 14) datetime.date(2023, 8, 11)
 datetime.date(2023, 8, 10) datetime.date(2023, 8, 9)
 datetime.date(2023, 8, 8) datetime.date(2023, 8, 7)
 datetime.date(2023, 8, 4) datetime.date(2023, 8, 3)
 datetime.date(2023, 8, 2) datetime.date(2023, 8, 1)
 datetime.date(2023, 7, 31) datetime.date(2023, 7, 28)
 datetime.date(2023, 7, 27) datetime.date(2023, 7, 26)
 datetime.date(2023, 7, 25) datetime.date(2023, 7, 24)
 datetime.date(2023, 7, 21) datetime.date(2023, 7, 20)
 datetime.date(2023, 7, 19) datetime.date(2023, 7, 18)
 datetime.date(2023, 7, 17) datetime.date(2023, 7, 14)
 datetime.date(2023, 7, 13) datetime.date(2023, 7, 12)
 datetime.date(2023, 7, 11) datetime.date(2023, 7, 10)
 datetime.date(2023, 7, 7) datetime.date(2023, 7, 6)
 datetime.date(2023, 7, 5) datetime.date(2023, 7, 4)
 datetime.date(2023, 7, 3) datetime.date(2023, 6, 30)
 datetime.date(2023, 6, 28) datetime.date(2023, 6, 27)
 datetime.date(2023, 6, 26) datetime.date(2023, 6, 23)
 datetime.date(2023, 6, 22) datetime.date(2023, 6, 21)
 datetime.date(2023, 6, 20) datetime.date(2023, 6, 19)
 datetime.date(2023, 6, 16) datetime.date(2023, 6, 15)
 datetime.date(2023, 6, 14) datetime.date(2023, 6, 13)
 datetime.date(2023, 6, 12) datetime.date(2023, 6, 9)
 datetime.date(2023, 6, 8) datetime.date(2023, 6, 7)
 datetime.date(2023, 6, 6) datetime.date(2023, 6, 5)
 datetime.date(2023, 6, 2) datetime.date(2023, 6, 1)
 datetime.date(2023, 5, 31) datetime.date(2023, 5, 30)
 datetime.date(2023, 5, 29) datetime.date(2023, 5, 26)
 datetime.date(2023, 5, 25) datetime.date(2023, 5, 24)
 datetime.date(2023, 5, 23) datetime.date(2023, 5, 22)
 datetime.date(2023, 5, 19) datetime.date(2023, 5, 18)
 datetime.date(2023, 5, 17) datetime.date(2023, 5, 16)
 datetime.date(2023, 5, 15) datetime.date(2023, 5, 12)
 datetime.date(2023, 5, 11) datetime.date(2023, 5, 10)
 datetime.date(2023, 5, 9) datetime.date(2023, 5, 8)
 datetime.date(2023, 5, 5) datetime.date(2023, 5, 4)
 datetime.date(2023, 5, 3) datetime.date(2023, 5, 2)
 datetime.date(2023, 4, 28) datetime.date(2023, 4, 27)
 datetime.date(2023, 4, 26) datetime.date(2023, 4, 25)
 datetime.date(2023, 4, 24) datetime.date(2023, 4, 21)
 datetime.date(2023, 4, 20) datetime.date(2023, 4, 19)
 datetime.date(2023, 4, 18) datetime.date(2023, 4, 17)
 datetime.date(2023, 4, 13) datetime.date(2023, 4, 12)
 datetime.date(2023, 4, 11) datetime.date(2023, 4, 10)
 datetime.date(2023, 4, 6) datetime.date(2023, 4, 5)
 datetime.date(2023, 4, 3) datetime.date(2023, 3, 31)
 datetime.date(2023, 3, 29) datetime.date(2023, 3, 28)
 datetime.date(2023, 3, 27) datetime.date(2023, 3, 24)
 datetime.date(2023, 3, 23) datetime.date(2023, 3, 22)
 datetime.date(2023, 3, 21) datetime.date(2023, 3, 20)
 datetime.date(2023, 3, 17) datetime.date(2023, 3, 16)
 datetime.date(2023, 3, 15) datetime.date(2023, 3, 14)
 datetime.date(2023, 3, 13) datetime.date(2023, 3, 10)
 datetime.date(2023, 3, 9) datetime.date(2023, 3, 8)
 datetime.date(2023, 3, 6) datetime.date(2023, 3, 3)
 datetime.date(2023, 3, 2) datetime.date(2023, 3, 1)
 datetime.date(2023, 2, 28) datetime.date(2023, 2, 27)
 datetime.date(2023, 2, 24) datetime.date(2023, 2, 23)
 datetime.date(2023, 2, 22) datetime.date(2023, 2, 21)
 datetime.date(2023, 2, 20) datetime.date(2023, 2, 17)
 datetime.date(2023, 2, 16) datetime.date(2023, 2, 15)
 datetime.date(2023, 2, 14) datetime.date(2023, 2, 13)
 datetime.date(2023, 2, 10) datetime.date(2023, 2, 9)
 datetime.date(2023, 2, 8) datetime.date(2023, 2, 7)
 datetime.date(2023, 2, 6) datetime.date(2023, 2, 3)
 datetime.date(2023, 2, 2) datetime.date(2023, 2, 1)
 datetime.date(2023, 1, 31) datetime.date(2023, 1, 30)
 datetime.date(2023, 1, 27) datetime.date(2023, 1, 25)
 datetime.date(2023, 1, 24) datetime.date(2023, 1, 23)
 datetime.date(2023, 1, 20) datetime.date(2023, 1, 19)
 datetime.date(2023, 1, 18) datetime.date(2023, 1, 17)
 datetime.date(2023, 1, 16) datetime.date(2023, 1, 13)
 datetime.date(2023, 1, 12) datetime.date(2023, 1, 11)
 datetime.date(2023, 1, 10) datetime.date(2023, 1, 9)
 datetime.date(2023, 1, 6) datetime.date(2023, 1, 5)
 datetime.date(2023, 1, 4) datetime.date(2023, 1, 3)
 datetime.date(2023, 1, 2)]

In [ ]:
# Convert the 'DATE1' column to datetime format
combined_df[' DATE1'] = pd.to_datetime(combined_df[' DATE1'])

# Sort the DataFrame by date in descending order
combined_df.sort_values(' DATE1', ascending=False, inplace=True)

## 1. LTP_CP

In [ ]:

print(combined_df[' DATE1'].unique())

['2024-01-19T00:00:00.000000000' '2024-01-18T00:00:00.000000000'
 '2024-01-17T00:00:00.000000000' '2024-01-16T00:00:00.000000000'
 '2024-01-15T00:00:00.000000000' '2024-01-12T00:00:00.000000000'
 '2024-01-11T00:00:00.000000000' '2024-01-10T00:00:00.000000000'
 '2024-01-09T00:00:00.000000000' '2024-01-08T00:00:00.000000000'
 '2024-01-05T00:00:00.000000000' '2024-01-04T00:00:00.000000000'
 '2024-01-03T00:00:00.000000000' '2024-01-02T00:00:00.000000000'
 '2024-01-01T00:00:00.000000000' '2023-12-29T00:00:00.000000000'
 '2023-12-28T00:00:00.000000000' '2023-12-27T00:00:00.000000000'
 '2023-12-26T00:00:00.000000000' '2023-12-22T00:00:00.000000000'
 '2023-12-21T00:00:00.000000000' '2023-12-20T00:00:00.000000000'
 '2023-12-19T00:00:00.000000000' '2023-12-18T00:00:00.000000000'
 '2023-12-15T00:00:00.000000000' '2023-12-14T00:00:00.000000000'
 '2023-12-13T00:00:00.000000000' '2023-12-12T00:00:00.000000000'
 '2023-12-11T00:00:00.000000000' '2023-12-08T00:00:00.000000000'
 '2023-12-07T00:00:00.000000000' '2023-12-06T00:00:00.000000000'
 '2023-12-05T00:00:00.000000000' '2023-12-04T00:00:00.000000000'
 '2023-12-01T00:00:00.000000000' '2023-11-30T00:00:00.000000000'
 '2023-11-29T00:00:00.000000000' '2023-11-28T00:00:00.000000000'
 '2023-11-24T00:00:00.000000000' '2023-11-23T00:00:00.000000000'
 '2023-11-22T00:00:00.000000000' '2023-11-21T00:00:00.000000000'
 '2023-11-20T00:00:00.000000000' '2023-11-17T00:00:00.000000000'
 '2023-11-16T00:00:00.000000000' '2023-11-15T00:00:00.000000000'
 '2023-11-13T00:00:00.000000000' '2023-11-12T00:00:00.000000000'
 '2023-11-10T00:00:00.000000000' '2023-11-09T00:00:00.000000000'
 '2023-11-08T00:00:00.000000000' '2023-11-07T00:00:00.000000000'
 '2023-11-06T00:00:00.000000000' '2023-11-03T00:00:00.000000000'
 '2023-11-02T00:00:00.000000000' '2023-11-01T00:00:00.000000000'
 '2023-10-31T00:00:00.000000000' '2023-10-30T00:00:00.000000000'
 '2023-10-27T00:00:00.000000000' '2023-10-26T00:00:00.000000000'
 '2023-10-25T00:00:00.000000000' '2023-10-23T00:00:00.000000000'
 '2023-10-20T00:00:00.000000000' '2023-10-19T00:00:00.000000000'
 '2023-10-18T00:00:00.000000000' '2023-10-17T00:00:00.000000000'
 '2023-10-16T00:00:00.000000000' '2023-10-13T00:00:00.000000000'
 '2023-10-12T00:00:00.000000000' '2023-10-11T00:00:00.000000000'
 '2023-10-10T00:00:00.000000000' '2023-10-09T00:00:00.000000000'
 '2023-10-06T00:00:00.000000000' '2023-10-05T00:00:00.000000000'
 '2023-10-04T00:00:00.000000000' '2023-10-03T00:00:00.000000000'
 '2023-09-29T00:00:00.000000000' '2023-09-28T00:00:00.000000000'
 '2023-09-27T00:00:00.000000000' '2023-09-26T00:00:00.000000000'
 '2023-09-25T00:00:00.000000000' '2023-09-22T00:00:00.000000000'
 '2023-09-21T00:00:00.000000000' '2023-09-20T00:00:00.000000000'
 '2023-09-18T00:00:00.000000000' '2023-09-15T00:00:00.000000000'
 '2023-09-14T00:00:00.000000000' '2023-09-13T00:00:00.000000000'
 '2023-09-12T00:00:00.000000000' '2023-09-11T00:00:00.000000000'
 '2023-09-08T00:00:00.000000000' '2023-09-07T00:00:00.000000000'
 '2023-09-06T00:00:00.000000000' '2023-09-05T00:00:00.000000000'
 '2023-09-04T00:00:00.000000000' '2023-09-01T00:00:00.000000000'
 '2023-08-31T00:00:00.000000000' '2023-08-30T00:00:00.000000000'
 '2023-08-29T00:00:00.000000000' '2023-08-28T00:00:00.000000000'
 '2023-08-25T00:00:00.000000000' '2023-08-24T00:00:00.000000000'
 '2023-08-23T00:00:00.000000000' '2023-08-22T00:00:00.000000000'
 '2023-08-21T00:00:00.000000000' '2023-08-18T00:00:00.000000000'
 '2023-08-17T00:00:00.000000000' '2023-08-16T00:00:00.000000000'
 '2023-08-14T00:00:00.000000000' '2023-08-11T00:00:00.000000000'
 '2023-08-10T00:00:00.000000000' '2023-08-09T00:00:00.000000000'
 '2023-08-08T00:00:00.000000000' '2023-08-07T00:00:00.000000000'
 '2023-08-04T00:00:00.000000000' '2023-08-03T00:00:00.000000000'
 '2023-08-02T00:00:00.000000000' '2023-08-01T00:00:00.000000000'
 '2023-07-31T00:00:00.000000000' '2023-07-28T00:00:00.000000000'
 '2023-07-27T00:00:00.000000000' '2023-07-26T00:00:00.000000000'
 '2023-07-25T00:00:00.000000000' '2023-07-24T00:00:00.000000000'
 '2023-07-21T00:00:00.000000000' '2023-07-20T00:00:00.000000000'
 '2023-07-19T00:00:00.000000000' '2023-07-18T00:00:00.000000000'
 '2023-07-17T00:00:00.000000000' '2023-07-14T00:00:00.000000000'
 '2023-07-13T00:00:00.000000000' '2023-07-12T00:00:00.000000000'
 '2023-07-11T00:00:00.000000000' '2023-07-10T00:00:00.000000000'
 '2023-07-07T00:00:00.000000000' '2023-07-06T00:00:00.000000000'
 '2023-07-05T00:00:00.000000000' '2023-07-04T00:00:00.000000000'
 '2023-07-03T00:00:00.000000000' '2023-06-30T00:00:00.000000000'
 '2023-06-28T00:00:00.000000000' '2023-06-27T00:00:00.000000000'
 '2023-06-26T00:00:00.000000000' '2023-06-23T00:00:00.000000000'
 '2023-06-22T00:00:00.000000000' '2023-06-21T00:00:00.000000000'
 '2023-06-20T00:00:00.000000000' '2023-06-19T00:00:00.000000000'
 '2023-06-16T00:00:00.000000000' '2023-06-15T00:00:00.000000000'
 '2023-06-14T00:00:00.000000000' '2023-06-13T00:00:00.000000000'
 '2023-06-12T00:00:00.000000000' '2023-06-09T00:00:00.000000000'
 '2023-06-08T00:00:00.000000000' '2023-06-07T00:00:00.000000000'
 '2023-06-06T00:00:00.000000000' '2023-06-05T00:00:00.000000000'
 '2023-06-02T00:00:00.000000000' '2023-06-01T00:00:00.000000000'
 '2023-05-31T00:00:00.000000000' '2023-05-30T00:00:00.000000000'
 '2023-05-29T00:00:00.000000000' '2023-05-26T00:00:00.000000000'
 '2023-05-25T00:00:00.000000000' '2023-05-24T00:00:00.000000000'
 '2023-05-23T00:00:00.000000000' '2023-05-22T00:00:00.000000000'
 '2023-05-19T00:00:00.000000000' '2023-05-18T00:00:00.000000000'
 '2023-05-17T00:00:00.000000000' '2023-05-16T00:00:00.000000000'
 '2023-05-15T00:00:00.000000000' '2023-05-12T00:00:00.000000000'
 '2023-05-11T00:00:00.000000000' '2023-05-10T00:00:00.000000000'
 '2023-05-09T00:00:00.000000000' '2023-05-08T00:00:00.000000000'
 '2023-05-05T00:00:00.000000000' '2023-05-04T00:00:00.000000000'
 '2023-05-03T00:00:00.000000000' '2023-05-02T00:00:00.000000000'
 '2023-04-28T00:00:00.000000000' '2023-04-27T00:00:00.000000000'
 '2023-04-26T00:00:00.000000000' '2023-04-25T00:00:00.000000000'
 '2023-04-24T00:00:00.000000000' '2023-04-21T00:00:00.000000000'
 '2023-04-20T00:00:00.000000000' '2023-04-19T00:00:00.000000000'
 '2023-04-18T00:00:00.000000000' '2023-04-17T00:00:00.000000000'
 '2023-04-13T00:00:00.000000000' '2023-04-12T00:00:00.000000000'
 '2023-04-11T00:00:00.000000000' '2023-04-10T00:00:00.000000000'
 '2023-04-06T00:00:00.000000000' '2023-04-05T00:00:00.000000000'
 '2023-04-03T00:00:00.000000000' '2023-03-31T00:00:00.000000000'
 '2023-03-29T00:00:00.000000000' '2023-03-28T00:00:00.000000000'
 '2023-03-27T00:00:00.000000000' '2023-03-24T00:00:00.000000000'
 '2023-03-23T00:00:00.000000000' '2023-03-22T00:00:00.000000000'
 '2023-03-21T00:00:00.000000000' '2023-03-20T00:00:00.000000000'
 '2023-03-17T00:00:00.000000000' '2023-03-16T00:00:00.000000000'
 '2023-03-15T00:00:00.000000000' '2023-03-14T00:00:00.000000000'
 '2023-03-13T00:00:00.000000000' '2023-03-10T00:00:00.000000000'
 '2023-03-09T00:00:00.000000000' '2023-03-08T00:00:00.000000000'
 '2023-03-06T00:00:00.000000000' '2023-03-03T00:00:00.000000000'
 '2023-03-02T00:00:00.000000000' '2023-03-01T00:00:00.000000000'
 '2023-02-28T00:00:00.000000000' '2023-02-27T00:00:00.000000000'
 '2023-02-24T00:00:00.000000000' '2023-02-23T00:00:00.000000000'
 '2023-02-22T00:00:00.000000000' '2023-02-21T00:00:00.000000000'
 '2023-02-20T00:00:00.000000000' '2023-02-17T00:00:00.000000000'
 '2023-02-16T00:00:00.000000000' '2023-02-15T00:00:00.000000000'
 '2023-02-14T00:00:00.000000000' '2023-02-13T00:00:00.000000000'
 '2023-02-10T00:00:00.000000000' '2023-02-09T00:00:00.000000000'
 '2023-02-08T00:00:00.000000000' '2023-02-07T00:00:00.000000000'
 '2023-02-06T00:00:00.000000000' '2023-02-03T00:00:00.000000000'
 '2023-02-02T00:00:00.000000000' '2023-02-01T00:00:00.000000000'
 '2023-01-31T00:00:00.000000000' '2023-01-30T00:00:00.000000000'
 '2023-01-27T00:00:00.000000000' '2023-01-25T00:00:00.000000000'
 '2023-01-24T00:00:00.000000000' '2023-01-23T00:00:00.000000000'
 '2023-01-20T00:00:00.000000000' '2023-01-19T00:00:00.000000000'
 '2023-01-18T00:00:00.000000000' '2023-01-17T00:00:00.000000000'
 '2023-01-16T00:00:00.000000000' '2023-01-13T00:00:00.000000000'
 '2023-01-12T00:00:00.000000000' '2023-01-11T00:00:00.000000000'
 '2023-01-10T00:00:00.000000000' '2023-01-09T00:00:00.000000000'
 '2023-01-06T00:00:00.000000000' '2023-01-05T00:00:00.000000000'
 '2023-01-04T00:00:00.000000000' '2023-01-03T00:00:00.000000000'
 '2023-01-02T00:00:00.000000000']

In [ ]:
# Filter the DataFrame to include only the latest date
combined_df[' DATE1'] = pd.to_datetime(combined_df[' DATE1'])
latest_date = combined_df[' DATE1'].max()

LTD = combined_df[combined_df[' DATE1'] == latest_date]
LTD

,SYMBOL,SERIES,OPEN_PRICE,HIGH_PRICE,LOW_PRICE,CLOSE_PRICE,LAST_PRICE,PREV_CLOSE,TTL_TRD_QNTY,TRD_VALUE,DATE1,TOTAL_TRADES,BODY,color
0,KEC,EQ,624.60,626.50,614.20,625.05,624.05,621.50,246701.0,1.535553e+08,2024-01-19,18048.0,0.45,green
1781,BRITANNIA,EQ,5029.00,5169.65,5012.30,5138.65,5142.35,5015.15,329252.0,1.682755e+09,2024-01-19,41510.0,109.65,green
1778,BPL,BE,89.80,91.00,89.00,91.00,91.00,86.70,136087.0,1.233691e+07,2024-01-19,661.0,1.20,green
1777,BPCL,EQ,476.00,485.00,474.05,480.95,480.40,473.20,6486928.0,3.111502e+09,2024-01-19,93715.0,4.95,green
1776,BOSCHLTD,EQ,22990.00,23262.70,22771.00,23184.30,23153.10,22813.90,19057.0,4.379773e+08,2024-01-19,6901.0,194.30,green
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
880,SHANTIGEAR,EQ,560.50,568.20,560.30,564.90,565.25,557.35,27674.0,1.559966e+07,2024-01-19,3791.0,4.40,green
881,SHARDACROP,EQ,440.00,443.70,428.45,432.70,433.35,436.80,86247.0,3.761361e+07,2024-01-19,8576.0,-7.30,red
882,SHARDAMOTR,EQ,1372.00,1410.55,1365.00,1401.30,1403.90,1364.90,18378.0,2.561225e+07,2024-01-19,3309.0,29.30,green
883,SHAREINDIA,EQ,1830.00,1830.00,1809.95,1820.35,1815.00,1811.40,46364.0,8.421625e+07,2024-01-19,3796.0,-9.65,red
885,SHARIABEES,EQ,501.35,502.93,496.97,501.92,502.93,496.79,1710.0,8.548202e+05,2024-01-19,87.0,0.57,green

In [ ]:
LTD['Prchng'] = 100*(LTD[' CLOSE_PRICE']-LTD[' PREV_CLOSE'])/LTD[' PREV_CLOSE']

/var/folders/b1/b6tfvntn1k3cvt9kyzby94gm0000gn/T/ipykernel_16756/3213031327.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  LTD['Prchng'] = 100*(LTD[' CLOSE_PRICE']-LTD[' PREV_CLOSE'])/LTD[' PREV_CLOSE']

In [ ]:
LTD['color'] = 'red'  # Initialize all rows to 'red'
LTD.loc[LTD[' OPEN_PRICE'] <= LTD[' CLOSE_PRICE'], 'color'] = 'green'

/var/folders/b1/b6tfvntn1k3cvt9kyzby94gm0000gn/T/ipykernel_16756/1971920360.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  LTD['color'] = 'red'  # Initialize all rows to 'red'

In [ ]:
#rEMOVING COMPANIES WITH CLOSE LESS THAN 9
LTD = LTD[LTD[' CLOSE_PRICE']>=9]

In [ ]:
#CONSIDERING TOTAL TRADED QUANTITY TO BE MORE THAN 99999
LTD = LTD[LTD[' TTL_TRD_QNTY']>99999]

In [ ]:
#CALCULATING PERCENTAGE CHANGE IN LTP VS CP PER CP OF STOCK = 100*(CP-LTP)/CP
#We want this to be negative i.e last trade price should be more than close price.

LTD[' LAST_PRICE'] = pd.to_numeric(LTD[' LAST_PRICE'], errors='coerce')
LTD[' CLOSE_PRICE'] = pd.to_numeric(LTD[' CLOSE_PRICE'], errors='coerce')
LTD['%ltp_vs_cp'] = 100*(LTD[' CLOSE_PRICE']-LTD[' LAST_PRICE'])/LTD[' CLOSE_PRICE']
LTD = LTD[LTD['%ltp_vs_cp']<0]

In [ ]:
#CALCULATING DIFFERENCE PERCENTAGE CHANGE IN PREV_CLOSE_PRICE AND CLOSE_PRICE WRT PREV_CLOSE_PRICE
#We are calculating indirectly daily return percentage for last day which should be positive.

LTD['%close_change'] = 100*(LTD[' CLOSE_PRICE']-LTD[' PREV_CLOSE'])/LTD[' PREV_CLOSE']
LTD = LTD[LTD['%close_change']>0]

In [ ]:
#CALCULATING DIFFERENCE PERCENTAGE CHANGE IN OPEN_PRICE AND CLOSE_PRICE WRT OPEN_PRICE
LTD['%open_close'] = 100*(LTD[' CLOSE_PRICE']-LTD[' OPEN_PRICE'])/LTD[' OPEN_PRICE']
LTD = LTD[LTD['%open_close']>0]

In [ ]:
#Filtering stocks with less than (-33.33%) of above value.

LTD['WeightVs%chg'] = 100*LTD['%ltp_vs_cp']/LTD['%open_close']
LTD = LTD[LTD['WeightVs%chg']<(-1)*33.33]

In [ ]:
LTD['WeightVs%Dchg'] = 100*LTD['%ltp_vs_cp']/LTD['%close_change']
LTD = LTD[LTD['WeightVs%Dchg']<(-1)*33.33]

In [ ]:
LTD['TYPE'] = 'LTP_CP'
LTD

,SYMBOL,SERIES,OPEN_PRICE,HIGH_PRICE,LOW_PRICE,CLOSE_PRICE,LAST_PRICE,PREV_CLOSE,TTL_TRD_QNTY,TRD_VALUE,...,TOTAL_TRADES,BODY,color,Prchng,%ltp_vs_cp,%close_change,%open_close,WeightVs%chg,WeightVs%Dchg,TYPE
1769,BLUESTARCO,EQ,1054.50,1114.80,1054.45,1073.55,1083.20,1049.25,338185.0,3.695830e+08,...,26624.0,19.05,green,2.315940,-0.898887,2.315940,1.806543,-49.757281,-38.813047,LTP_CP
1898,CROMPTON,EQ,311.20,315.70,308.65,311.35,312.30,309.40,1518396.0,4.730617e+08,...,35699.0,0.15,green,0.630252,-0.305123,0.630252,0.048201,-633.028210,-48.412826,LTP_CP
1874,CONCOR,EQ,850.00,867.65,840.60,858.70,864.90,843.65,1564164.0,1.326138e+09,...,84142.0,8.70,green,1.783915,-0.722022,1.783915,1.023529,-70.542346,-40.473992,LTP_CP
1314,WELSPUNLIV,EQ,149.50,152.95,149.50,150.70,151.30,149.05,1183141.0,1.788820e+08,...,14810.0,1.20,green,1.107011,-0.398142,1.107011,0.802676,-49.601858,-35.965494,LTP_CP
1603,ARTEMISMED,EQ,184.00,190.00,182.95,185.95,187.00,184.45,196625.0,3.658279e+07,...,9167.0,1.95,green,0.813229,-0.564668,0.813229,1.059783,-53.281486,-69.435332,LTP_CP
1579,APLLTD,EQ,938.90,945.90,922.80,943.45,945.60,940.40,251735.0,2.367273e+08,...,20639.0,4.55,green,0.324330,-0.227887,0.324330,0.484610,-47.024860,-70.263916,LTP_CP
2458,INDOCO,EQ,380.50,388.70,377.10,380.70,385.00,379.55,125111.0,4.765662e+07,...,8859.0,0.20,green,0.302990,-1.129498,0.302990,0.052562,-2148.870502,-372.783545,LTP_CP
2299,HFCL,EQ,85.10,90.95,83.80,88.55,90.70,84.60,32726022.0,2.845237e+09,...,65901.0,3.45,green,4.669031,-2.428007,4.669031,4.054054,-59.890834,-52.002373,LTP_CP
2611,KANORICHEM,EQ,138.35,142.45,137.75,138.80,139.50,137.40,127413.0,1.778361e+07,...,3408.0,0.45,green,1.018923,-0.504323,1.018923,0.325262,-155.051233,-49.495677,LTP_CP
2551,JAYSREETEA,EQ,114.95,116.50,113.40,115.25,116.30,113.60,118801.0,1.367079e+07,...,2626.0,0.30,green,1.452465,-0.911063,1.452465,0.260983,-349.088937,-62.725301,LTP_CP
2038,EKC,EQ,135.00,137.65,134.55,135.25,135.75,134.05,559022.0,7.577133e+07,...,6721.0,0.25,green,0.895188,-0.369686,0.895188,0.185185,-199.630314,-41.296981,LTP_CP
2217,GREENPLY,EQ,237.10,245.90,236.50,238.35,240.00,236.75,271941.0,6.554140e+07,...,9732.0,1.25,green,0.675818,-0.692259,0.675818,0.527204,-131.307741,-102.432741,LTP_CP
2210,GRASIM,EQ,2056.45,2094.00,2052.35,2081.20,2091.00,2053.65,456698.0,9.470394e+08,...,48168.0,24.75,green,1.341514,-0.470882,1.341514,1.203530,-39.125077,-35.100806,LTP_CP
2198,GOLDSHARE,EQ,52.85,53.15,52.80,53.00,53.10,52.85,133261.0,7.047708e+06,...,2867.0,0.15,green,0.283822,-0.188679,0.283822,0.283822,-66.477987,-66.477987,LTP_CP
2131,GANESHBE,EQ,165.05,167.80,163.00,165.50,166.00,164.35,417795.0,6.923923e+07,...,10216.0,0.45,green,0.699726,-0.302115,0.699726,0.272645,-110.808996,-43.176146,LTP_CP
457,ORIENTALTL,EQ,9.60,9.95,9.60,9.65,9.70,9.55,134329.0,1.304364e+06,...,592.0,0.05,green,1.047120,-0.518135,1.047120,0.520833,-99.481865,-49.481865,LTP_CP
336,NAVA,EQ,462.80,469.00,462.10,465.90,468.00,460.25,221182.0,1.029867e+08,...,9882.0,3.10,green,1.227594,-0.450741,1.227594,0.669836,-67.291195,-36.717401,LTP_CP
358,NESTLEIND,EQ,2510.00,2521.90,2499.70,2514.15,2520.00,2502.00,941391.0,2.362408e+09,...,73734.0,4.15,green,0.485612,-0.232683,0.485612,0.165339,-140.731172,-47.915465,LTP_CP
553,POWERGRID,EQ,235.00,236.95,232.40,235.40,236.85,233.45,20931080.0,4.895002e+09,...,156147.0,0.40,green,0.835297,-0.615973,0.835297,0.170213,-361.884027,-73.743002,LTP_CP
590,PSUBNKIETF,EQ,59.65,60.00,59.25,59.70,60.00,58.96,653769.0,3.899918e+07,...,755.0,0.05,green,1.255088,-0.502513,1.255088,0.083822,-599.497487,-40.038028,LTP_CP
101,LGBFORGE,EQ,12.10,12.40,12.00,12.15,12.20,12.10,249363.0,3.042962e+06,...,965.0,0.05,green,0.413223,-0.411523,0.413223,0.413223,-99.588477,-99.588477,LTP_CP
88,LAOPALA,EQ,355.15,363.15,355.15,358.70,361.55,354.10,101539.0,3.631718e+07,...,6484.0,3.55,green,1.299068,-0.794536,1.299068,0.999578,-79.487154,-61.161986,LTP_CP
19,KIOCL,EQ,371.00,380.50,370.00,372.20,374.95,366.50,179594.0,6.721328e+07,...,5393.0,1.20,green,1.555252,-0.738850,1.555252,0.323450,-228.427817,-47.506764,LTP_CP
71,KSCL,EQ,666.45,685.75,666.45,674.10,676.80,666.40,171463.0,1.159655e+08,...,13180.0,7.65,green,1.155462,-0.400534,1.155462,1.147873,-34.893584,-34.664401,LTP_CP
56,KPIGREEN,EQ,1415.00,1435.00,1391.50,1424.65,1434.00,1406.70,142500.0,2.013350e+08,...,10335.0,9.65,green,1.276036,-0.656302,1.276036,0.681979,-96.234890,-51.432835,LTP_CP
258,MIRCELECTR,BE,16.65,17.30,16.55,16.80,16.95,16.70,210843.0,3.575918e+06,...,447.0,0.15,green,0.598802,-0.892857,0.598802,0.900901,-99.107143,-149.107143,LTP_CP
167,MAHKTECH,EQ,12.64,12.89,12.54,12.80,12.86,12.64,1639657.0,2.079718e+07,...,2916.0,0.16,green,1.265823,-0.468750,1.265823,1.265823,-37.031250,-37.031250,LTP_CP
1064,SYNCOMF,EQ,15.35,16.05,15.30,15.75,16.00,15.30,4452936.0,6.926896e+07,...,9832.0,0.40,green,2.941176,-1.587302,2.941176,2.605863,-60.912698,-53.968254,LTP_CP
1005,STCINDIA,EQ,161.10,166.70,160.50,163.60,165.00,159.90,459264.0,7.516752e+07,...,11937.0,2.50,green,2.313946,-0.855746,2.313946,1.551831,-55.144254,-36.982092,LTP_CP
759,SAREGAMA,EQ,345.25,350.00,340.05,345.70,348.50,342.85,366870.0,1.260642e+08,...,18716.0,0.45,green,0.831267,-0.809951,0.831267,0.130340,-621.412271,-97.435663,LTP_CP
681,RISHABH,EQ,571.10,585.00,568.30,576.45,580.00,569.75,139435.0,8.004887e+07,...,10132.0,5.35,green,1.175954,-0.615838,1.175954,0.936789,-65.739302,-52.369236,LTP_CP
936,SILVERIETF,EQ,72.62,72.91,72.41,72.69,72.78,72.50,215113.0,1.563192e+07,...,1088.0,0.07,green,0.262069,-0.123813,0.262069,0.096392,-128.447615,-47.244608,LTP_CP

In [ ]:
"""LTD[' DELIV_PER'] = pd.to_numeric(LTD[' DELIV_PER'], errors='coerce')
LTD = LTD[LTD[' DELIV_PER']>51.00]"""

"LTD[' DELIV_PER'] = pd.to_numeric(LTD[' DELIV_PER'], errors='coerce')\nLTD = LTD[LTD[' DELIV_PER']>51.00]"

In [ ]:
LTD.to_csv("ltp_cp.csv",index=False)

## THREE WHITE SOLDIERS

In [ ]:
# Get the unique dates in the 'DATE1' column
unique_dates = combined_df[' DATE1'].unique()

# Get the last two dates from the unique dates
last_two_dates = unique_dates[:3]  # Change this line to select the last two dates

# Filter the DataFrame to keep only the rows for the last two dates
LTD2 = combined_df[combined_df[' DATE1'].isin(last_two_dates)]

In [ ]:
"""columns_to_drop = LTD2.columns[df.columns.get_loc(' CLOSE_PRICE')+1:]
LTD2 = LTD2.drop(columns=columns_to_drop)
LTD2"""

"columns_to_drop = LTD2.columns[df.columns.get_loc(' CLOSE_PRICE')+1:]\nLTD2 = LTD2.drop(columns=columns_to_drop)\nLTD2"

In [ ]:
LTD2 = LTD2.sort_values(by=['SYMBOL', ' DATE1'], ascending=[True, True])

In [ ]:
LTD2['color'] = 'red'  # Initialize all rows to 'red'
LTD2.loc[LTD2[' OPEN_PRICE'] <= LTD2[' CLOSE_PRICE'], 'color'] = 'green'

In [ ]:
#% change
LTD2['Prchng'] = 100*(LTD2[' CLOSE_PRICE']-LTD2[' PREV_CLOSE'])/LTD2[' PREV_CLOSE']

#candle
LTD2['CANDLE'] = abs(LTD2[' HIGH_PRICE'] - LTD2[' LOW_PRICE'])

#body in candle
LTD2['BODY'] = abs(-LTD2[' OPEN_PRICE'] + LTD2[' CLOSE_PRICE'])

#Body %
LTD2['BODY%'] = 100*(LTD2['BODY']/LTD2['CANDLE'])

In [ ]:
# Convert the 'date_column' to datetime format
LTD2[' DATE1'] = pd.to_datetime(LTD2[' DATE1'])

In [ ]:
latest_date = LTD2[' DATE1'].max().date()
LTD2['script'] = LTD2.apply(lambda row: 1 if(row[' DATE1'].date() == latest_date) else 0, axis = 1)

In [ ]:
LTD2.sort_values(['SYMBOL', ' DATE1'], inplace=True)

### THREE WHITE SOLDIERS

In [ ]:
# Sort the DataFrame by symbol and date


# Filter stocks with bullish engulfing pattern
filtered_stocks = LTD2.groupby('SYMBOL').apply(lambda x: (x['script'] == 1) &
                                                       (x['BODY%'] > 65 ) &
                                                       (x['Prchng']>=2.5) &
                                                       (x['Prchng'].shift()>=2.5) &
                                                       (x['Prchng'].shift(2)>=2.5) &
                                                       ((x[' OPEN_PRICE'].shift(2)-x[' CLOSE_PRICE'].shift(2))<0) &
                                                       ((x[' OPEN_PRICE'].shift()-x[' CLOSE_PRICE'].shift())<0) &
                                                       ((x[' OPEN_PRICE']-x[' CLOSE_PRICE'])<0)
                                                       )


# Reset index to remove the groupby index
filtered_stocks = filtered_stocks.reset_index(level=0, drop=True)

# Get the names of stocks with bullish engulfing pattern
stock_names = filtered_stocks[filtered_stocks].index.unique()

# Print the stock names
# Get the rows based on the indexes
bullen = LTD2.loc[stock_names]
bullen['TYPE'] = 'threewhitesoldiers'
bullen.to_csv("threewhitesoldiers.csv",index=False)
bullen

,SYMBOL,SERIES,OPEN_PRICE,HIGH_PRICE,LOW_PRICE,CLOSE_PRICE,LAST_PRICE,PREV_CLOSE,TTL_TRD_QNTY,TRD_VALUE,DATE1,TOTAL_TRADES,BODY,color,Prchng,CANDLE,BODY%,script,TYPE
1482,ACCURACY,BE,14.0,14.15,14.00,14.15,14.15,13.50,575759.0,8.132055e+06,2024-01-19,711.0,0.15,green,4.814815,0.15,100.000000,1,threewhitesoldiers
1703,BANKA,BE,133.0,140.25,133.00,138.05,139.50,133.70,115963.0,1.597828e+07,2024-01-19,825.0,5.05,green,3.253553,7.25,69.655172,1,threewhitesoldiers
229,MEDANTA,EQ,1065.0,1098.00,1060.55,1093.65,1095.05,1061.25,490308.0,5.320672e+08,2024-01-19,49857.0,28.65,green,3.053004,37.45,76.502003,1,threewhitesoldiers
473,PAKKA,EQ,330.0,378.90,328.05,371.25,371.00,323.35,2192409.0,7.805178e+08,2024-01-19,74522.0,41.25,green,14.813669,50.85,81.120944,1,threewhitesoldiers

### THREE BLACK CROWS

In [ ]:
# Sort the DataFrame by symbol and date


# Filter stocks with bullish engulfing pattern
filtered_stocks = LTD2.groupby('SYMBOL').apply(lambda x: (x['script'] == 1) &
                                                       (x['BODY%'] > 65 ) &
                                                       (x['Prchng']<=-2.5) &
                                                       (x['Prchng'].shift()<=-2.5) &
                                                       (x['Prchng'].shift(2)<=-2.5) &
                                                       ((x[' OPEN_PRICE'].shift(2)-x[' CLOSE_PRICE'].shift(2))>0) &
                                                       ((x[' OPEN_PRICE'].shift()-x[' CLOSE_PRICE'].shift())>0) &
                                                       ((x[' OPEN_PRICE']-x[' CLOSE_PRICE'])>0)
                                                       )


# Reset index to remove the groupby index
filtered_stocks = filtered_stocks.reset_index(level=0, drop=True)

# Get the names of stocks with bullish engulfing pattern
stock_names = filtered_stocks[filtered_stocks].index.unique()

# Print the stock names
# Get the rows based on the indexes
tbc = LTD2.loc[stock_names]
tbc['TYPE'] = 'threeblackcrows'
tbc.to_csv("threeblackcrows.csv",index=False)
tbc

,SYMBOL,SERIES,OPEN_PRICE,HIGH_PRICE,LOW_PRICE,CLOSE_PRICE,LAST_PRICE,PREV_CLOSE,TTL_TRD_QNTY,TRD_VALUE,DATE1,TOTAL_TRADES,BODY,color,Prchng,CANDLE,BODY%,script,TYPE
196,MANYAVAR,EQ,1130.0,1130.25,1080.0,1088.05,1091.0,1120.4,410871.0,4.518575e+08,2024-01-19,65082.0,41.95,red,-2.887362,50.25,83.482587,1,threeblackcrows

### BEARISH HARAMI CROSS

In [ ]:
# Sort the DataFrame by symbol and date


# Filter stocks with bullish engulfing pattern
filtered_stocks = LTD2.groupby('SYMBOL').apply(lambda x: (x['script'] == 1) &
                                                       (x['BODY%'] > 65 ) &
                                                       (x['BODY%'].shift() < 25 ) &
                                                       (x['BODY%'].shift(2) > 65 ) &
                                                       ((x[' OPEN_PRICE']-x[' CLOSE_PRICE'])>0) & #latest candle red hai
                                                       ((x[' OPEN_PRICE'].shift(2)-x[' CLOSE_PRICE'].shift(2))<0) & # 1st candle green
                                                       (x[' LOW_PRICE']<x[' LOW_PRICE'].shift(2))
                                                       )


# Reset index to remove the groupby index
filtered_stocks = filtered_stocks.reset_index(level=0, drop=True)

# Get the names of stocks with bullish engulfing pattern
stock_names = filtered_stocks[filtered_stocks].index.unique()

# Print the stock names
# Get the rows based on the indexes
M = LTD2.loc[stock_names]
M['TYPE'] = 'M'
M.to_csv("M.csv",index=False)
M

Empty DataFrame
Columns: [SYMBOL,  SERIES,  OPEN_PRICE,  HIGH_PRICE,  LOW_PRICE,  CLOSE_PRICE,  LAST_PRICE,  PREV_CLOSE,  TTL_TRD_QNTY, TRD_VALUE,  DATE1, TOTAL_TRADES, BODY, color, Prchng, CANDLE, BODY%, script, TYPE]
Index: []

### BULLISH HARAMI CROSS

In [ ]:
# Sort the DataFrame by symbol and date


# Filter stocks with bullish engulfing pattern
filtered_stocks = LTD2.groupby('SYMBOL').apply(lambda x: (x['script'] == 1) &
                                                       (x['BODY%'] > 65 ) &
                                                       (x['BODY%'].shift() < 15 ) &
                                                       (x['BODY%'].shift(2) > 65 ) &
                                                       ((x[' OPEN_PRICE']-x[' CLOSE_PRICE'])<0) & # latest candle green
                                                       ((x[' OPEN_PRICE'].shift(2)-x[' CLOSE_PRICE'].shift(2))>0) & # 1st candle red
                                                       (x[' HIGH_PRICE'].shift(2)<x[' HIGH_PRICE'])
                                                       )


# Reset index to remove the groupby index
filtered_stocks = filtered_stocks.reset_index(level=0, drop=True)

# Get the names of stocks with bullish engulfing pattern
stock_names = filtered_stocks[filtered_stocks].index.unique()

# Print the stock names
# Get the rows based on the indexes
W = LTD2.loc[stock_names]
W['TYPE'] = 'W'
W.to_csv("W.csv",index=False)
W

,SYMBOL,SERIES,OPEN_PRICE,HIGH_PRICE,LOW_PRICE,CLOSE_PRICE,LAST_PRICE,PREV_CLOSE,TTL_TRD_QNTY,TRD_VALUE,DATE1,TOTAL_TRADES,BODY,color,Prchng,CANDLE,BODY%,script,TYPE
1884,COROMANDEL,EQ,1156.05,1185.65,1152.7,1182.70,1180.60,1152.70,177261.0,2.077008e+08,2024-01-19,13202.0,26.65,green,2.602585,32.95,80.880121,1,W
1982,DOLLAR,EQ,447.50,461.30,446.5,458.95,458.50,444.75,101631.0,4.630006e+07,2024-01-19,7391.0,11.45,green,3.192805,14.80,77.364865,1,W
2047,EMAMIPAP,EQ,120.45,133.50,120.0,132.35,132.60,119.80,1111895.0,1.444723e+08,2024-01-19,8543.0,11.90,green,10.475793,13.50,88.148148,1,W
2170,GLOBALVECT,BE,120.10,128.95,120.1,128.95,128.95,122.85,22162.0,2.843699e+06,2024-01-19,161.0,8.85,green,4.965405,8.85,100.000000,1,W
179,MANAKALUCO,EQ,29.45,31.90,29.3,31.60,31.55,28.80,729873.0,2.262273e+07,2024-01-19,2919.0,2.15,green,9.722222,2.60,82.692308,1,W
282,MON100,EQ,136.10,137.79,136.1,137.58,137.65,135.73,783334.0,1.076223e+08,2024-01-19,6894.0,1.48,green,1.363000,1.69,87.573964,1,W

## CHARTS AND PATTERN

In [ ]:
# Get the last two dates from the unique dates
last_two_dates = unique_dates[:252]  # Change this line to select the last two dates

# Filter the DataFrame to keep only the rows for the last two dates
LTD3 = combined_df[combined_df[' DATE1'].isin(last_two_dates)]

In [ ]:
"""columns_to_drop = LTD.columns[df.columns.get_loc(' CLOSE_PRICE')+1:]
LTD3 = LTD.drop(columns=columns_to_drop)
LTD = LTD.sort_values(by=['SYMBOL', ' DATE1'], ascending=[True, True])"""

"columns_to_drop = LTD.columns[df.columns.get_loc(' CLOSE_PRICE')+1:]\nLTD3 = LTD.drop(columns=columns_to_drop)\nLTD = LTD.sort_values(by=['SYMBOL', ' DATE1'], ascending=[True, True])"

In [ ]:
LTD3['color'] = 'red'  # Initialize all rows to 'red'
LTD3.loc[LTD3[' OPEN_PRICE'] <= LTD3[' CLOSE_PRICE'], 'color'] = 'green'

/var/folders/b1/b6tfvntn1k3cvt9kyzby94gm0000gn/T/ipykernel_16756/1648147776.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  LTD3['color'] = 'red'  # Initialize all rows to 'red'

In [ ]:
#% change
LTD3['Prchng'] = 100*(LTD3[' CLOSE_PRICE']-LTD3[' PREV_CLOSE'])/LTD3[' PREV_CLOSE']

#candle
LTD3['CANDLE'] = abs(LTD3[' HIGH_PRICE'] - LTD3[' LOW_PRICE'])

#body in candle
LTD3['BODY'] = (-LTD3[' OPEN_PRICE'] + LTD3[' CLOSE_PRICE'])

#Body %
LTD3['BODY%'] = 100*(LTD3['BODY']/LTD3['CANDLE'])

/var/folders/b1/b6tfvntn1k3cvt9kyzby94gm0000gn/T/ipykernel_16756/2298273482.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  LTD3['Prchng'] = 100*(LTD3[' CLOSE_PRICE']-LTD3[' PREV_CLOSE'])/LTD3[' PREV_CLOSE']
/var/folders/b1/b6tfvntn1k3cvt9kyzby94gm0000gn/T/ipykernel_16756/2298273482.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  LTD3['CANDLE'] = abs(LTD3[' HIGH_PRICE'] - LTD3[' LOW_PRICE'])
/var/folders/b1/b6tfvntn1k3cvt9kyzby94gm0000gn/T/ipykernel_16756/2298273482.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  LTD3['BODY'] = (-LTD3[' OPEN_PRICE'] + LTD3[' CLOSE_PRICE'])
/var/folders/b1/b6tfvntn1k3cvt9kyzby94gm0000gn/T/ipykernel_16756/2298273482.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  LTD3['BODY%'] = 100*(LTD3['BODY']/LTD3['CANDLE'])

In [ ]:
# Convert the 'date_column' to datetime format
LTD3[' DATE1'] = pd.to_datetime(LTD3[' DATE1'])

/var/folders/b1/b6tfvntn1k3cvt9kyzby94gm0000gn/T/ipykernel_16756/4045922834.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  LTD3[' DATE1'] = pd.to_datetime(LTD3[' DATE1'])

In [ ]:
latest_date = LTD3[' DATE1'].max().date()
LTD3['script'] = LTD3.apply(lambda row: 1 if(row[' DATE1'].date() == latest_date) else 0, axis = 1)
LTD3.sort_values(['SYMBOL', ' DATE1'], inplace=True)
LTD3

/var/folders/b1/b6tfvntn1k3cvt9kyzby94gm0000gn/T/ipykernel_16756/3347810456.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  LTD3['script'] = LTD3.apply(lambda row: 1 if(row[' DATE1'].date() == latest_date) else 0, axis = 1)
/var/folders/b1/b6tfvntn1k3cvt9kyzby94gm0000gn/T/ipykernel_16756/3347810456.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  LTD3.sort_values(['SYMBOL', ' DATE1'], inplace=True)

,SYMBOL,SERIES,OPEN_PRICE,HIGH_PRICE,LOW_PRICE,CLOSE_PRICE,LAST_PRICE,PREV_CLOSE,TTL_TRD_QNTY,TRD_VALUE,DATE1,TOTAL_TRADES,BODY,color,Prchng,CANDLE,BODY%,script
623739,20MICRONS,EQ,89.75,91.00,89.75,90.80,90.90,89.40,52956.0,4794646.95,2023-01-13,1039.0,1.05,green,1.565996,1.25,84.000000,0
619162,20MICRONS,EQ,90.95,91.90,89.55,89.95,89.55,90.80,71845.0,6513385.75,2023-01-16,959.0,-1.00,red,-0.936123,2.35,-42.553191,0
616875,20MICRONS,EQ,90.00,90.50,88.25,89.00,89.50,89.95,85757.0,7632798.55,2023-01-17,1734.0,-1.00,red,-1.056142,2.25,-44.444444,0
614587,20MICRONS,EQ,89.45,90.25,89.00,89.85,89.85,89.00,30619.0,2745627.95,2023-01-18,1143.0,0.40,green,0.955056,1.25,32.000000,0
612300,20MICRONS,EQ,89.25,91.00,88.75,89.55,90.10,89.85,65804.0,5921048.70,2023-01-19,1405.0,0.30,green,-0.333890,2.25,13.333333,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12806,ZYDUSWELL,EQ,1639.10,1650.00,1621.05,1642.55,1648.00,1634.20,20184.0,33029457.10,2024-01-15,3835.0,3.45,green,0.510953,28.95,11.917098,0
8227,ZYDUSWELL,EQ,1647.50,1659.15,1632.00,1643.30,1648.00,1642.55,14509.0,23838740.80,2024-01-16,3181.0,-4.20,red,0.045661,27.15,-15.469613,0
5937,ZYDUSWELL,EQ,1626.00,1640.90,1610.00,1617.15,1613.00,1643.30,19117.0,31061045.65,2024-01-17,3703.0,-8.85,red,-1.591310,30.90,-28.640777,0
3650,ZYDUSWELL,EQ,1617.15,1626.00,1585.00,1617.35,1620.00,1617.15,14740.0,23740493.90,2024-01-18,3539.0,0.20,green,0.012367,41.00,0.487805,0
1361,ZYDUSWELL,EQ,1635.00,1637.00,1614.80,1621.70,1615.05,1617.35,13880.0,22581777.05,2024-01-19,2514.0,-13.30,red,0.268958,22.20,-59.909910,1

### BULLISH ENGULFING

In [ ]:
# Sort the DataFrame by symbol and date
LTD3.sort_values(['SYMBOL', ' DATE1'], inplace=True)

# Filter stocks with bullish engulfing pattern
filtered_stocks = LTD3.groupby('SYMBOL').apply(lambda x: (x['script'] == 1) &
                                                       (x[' OPEN_PRICE'] < x[' LOW_PRICE'].shift()) &
                                                       (x[' CLOSE_PRICE'] > x[' HIGH_PRICE'].shift()) &
                                                       (x['BODY'].shift()<0) &
                                                       (x[' CLOSE_PRICE']>x[' OPEN_PRICE']) & (x[' CLOSE_PRICE'].shift()<x[' OPEN_PRICE'].shift()) )


# Reset index to remove the groupby index
filtered_stocks = filtered_stocks.reset_index(level=0, drop=True)

# Get the names of stocks with bullish engulfing pattern
stock_names = filtered_stocks[filtered_stocks].index.unique()

# Print the stock names
# Get the rows based on the indexes
bullen = LTD3.loc[stock_names]
bullen['TYPE'] = 'bullengulfing'
bullen.to_csv("bullengulfing.csv",index=False)
bullen

/var/folders/b1/b6tfvntn1k3cvt9kyzby94gm0000gn/T/ipykernel_16756/434844918.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  LTD3.sort_values(['SYMBOL', ' DATE1'], inplace=True)

,SYMBOL,SERIES,OPEN_PRICE,HIGH_PRICE,LOW_PRICE,CLOSE_PRICE,LAST_PRICE,PREV_CLOSE,TTL_TRD_QNTY,TRD_VALUE,DATE1,TOTAL_TRADES,BODY,color,Prchng,CANDLE,BODY%,script,TYPE
1998,DSPN50ETF,EQ,215.56,222.35,215.56,221.39,220.9,219.96,873.0,193143.84,2024-01-19,48.0,5.83,green,0.650118,6.79,85.861561,1,bullengulfing

BEARISH ENGULFING

In [ ]:
# Sort the DataFrame by symbol and date
LTD3.sort_values(['SYMBOL', ' DATE1'], inplace=True)

# Filter stocks with bearish engulfing pattern
filtered_stocks = LTD3.groupby('SYMBOL').apply(lambda x: (x['script'] == 1) &
                                                       (x[' CLOSE_PRICE'] < x[' LOW_PRICE'].shift()) &
                                                       (x[' OPEN_PRICE'] > x[' HIGH_PRICE'].shift()) &
                                                (x['BODY'].shift()>0) &
                                              (x[' CLOSE_PRICE']<x[' OPEN_PRICE']) & (x[' CLOSE_PRICE'].shift()>x[' OPEN_PRICE'].shift())
                                             )

# Reset index to remove the groupby index
filtered_stocks = filtered_stocks.reset_index(level=0, drop=True)

# Get the names of stocks with bearish engulfing pattern
stock_names = filtered_stocks[filtered_stocks].index.unique()

# Print the stock names
# Get the rows based on the indexes

bearen = LTD3.loc[stock_names]
bearen['TYPE'] = 'bearengulfing'
bearen.to_csv("bearengulfing.csv",index=False)
bearen

/var/folders/b1/b6tfvntn1k3cvt9kyzby94gm0000gn/T/ipykernel_16756/1988017092.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  LTD3.sort_values(['SYMBOL', ' DATE1'], inplace=True)

,SYMBOL,SERIES,OPEN_PRICE,HIGH_PRICE,LOW_PRICE,CLOSE_PRICE,LAST_PRICE,PREV_CLOSE,TTL_TRD_QNTY,TRD_VALUE,DATE1,TOTAL_TRADES,BODY,color,Prchng,CANDLE,BODY%,script,TYPE
1797,BYKE,BE,71.0,71.0,69.00,69.00,69.00,70.2,43658.0,3068651.75,2024-01-19,129.0,-2.00,red,-1.709402,2.00,-100.000000,1,bearengulfing
717,RVHL,EQ,63.9,63.9,57.85,58.45,57.85,60.9,580685.0,36537273.20,2024-01-19,2051.0,-5.45,red,-4.022989,6.05,-90.082645,1,bearengulfing

### BEARISH NEWS CANDLE

In [ ]:
# Sort the DataFrame by symbol and date
LTD3.sort_values(['SYMBOL', ' DATE1'], inplace=True)

# Filter stocks with bullish NEWS pattern
filtered_stocks = LTD3.groupby('SYMBOL').apply(lambda x: (x['script'] == 1) & (x[' LOW_PRICE'] > (x[' HIGH_PRICE'].shift())) &
                                                       ((x[' OPEN_PRICE'] - x[' CLOSE_PRICE'])>0))


# Reset index to remove the groupby index
filtered_stocks = filtered_stocks.reset_index(level=0, drop=True)

# Get the names of stocks with news candle pattern
stock_names = filtered_stocks[filtered_stocks].index.unique()

# Print the stock names
# Get the rows based on the indexes
bearishnews = LTD3.loc[stock_names]
bearishnews['TYPE'] = 'bearishnews'
bearishnews.to_csv("bearishnews.csv",index=False)
bearishnews

/var/folders/b1/b6tfvntn1k3cvt9kyzby94gm0000gn/T/ipykernel_16756/2712670447.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  LTD3.sort_values(['SYMBOL', ' DATE1'], inplace=True)

,SYMBOL,SERIES,OPEN_PRICE,HIGH_PRICE,LOW_PRICE,CLOSE_PRICE,LAST_PRICE,PREV_CLOSE,TTL_TRD_QNTY,TRD_VALUE,DATE1,TOTAL_TRADES,BODY,color,Prchng,CANDLE,BODY%,script,TYPE
1478,ABSLNN50ET,EQ,57.00,57.00,55.90,56.34,56.32,55.70,3491.0,1.960977e+05,2024-01-19,110.0,-0.66,red,1.149013,1.10,-60.000000,1,bearishnews
1853,CINELINE,BE,147.95,147.95,146.00,146.00,146.00,145.95,10365.0,1.527246e+06,2024-01-19,58.0,-1.95,red,0.034258,1.95,-100.000000,1,bearishnews
1899,CROWN,BE,123.40,123.40,122.00,122.05,122.05,121.00,4155.0,5.106466e+05,2024-01-19,40.0,-1.35,red,0.867769,1.40,-96.428571,1,bearishnews
2054,EMSLIMITED,EQ,475.00,481.60,466.20,474.90,472.00,458.70,1583095.0,7.547298e+08,2024-01-19,15740.0,-0.10,red,3.531720,15.40,-0.649351,1,bearishnews
2277,HDFCNIFIT,EQ,378.50,380.97,374.42,376.16,376.16,373.26,1188.0,4.468723e+05,2024-01-19,78.0,-2.34,red,0.776938,6.55,-35.725191,1,bearishnews
2479,INNOVACAP,EQ,577.35,583.90,531.40,539.45,535.00,519.20,1243047.0,6.868350e+08,2024-01-19,42083.0,-37.90,red,3.900231,52.50,-72.190476,1,bearishnews
2614,KAPSTON,BE,304.00,304.10,295.00,296.55,302.00,289.65,10313.0,3.105161e+06,2024-01-19,182.0,-7.45,red,2.382185,9.10,-81.868132,1,bearishnews
107,LICMFGOLD,EQ,5719.70,5719.70,5666.00,5688.00,5688.00,5659.90,67.0,3.809548e+05,2024-01-19,31.0,-31.70,red,0.496475,53.70,-59.031657,1,bearishnews
152,MADHAV,BE,70.65,71.70,69.15,70.40,70.10,68.40,18348.0,1.297421e+06,2024-01-19,215.0,-0.25,red,2.923977,2.55,-9.803922,1,bearishnews
408,NKIND,BE,58.95,58.95,58.20,58.20,58.20,57.85,1750.0,1.030450e+05,2024-01-19,5.0,-0.75,red,0.605013,0.75,-100.000000,1,bearishnews
441,OMAXAUTO,EQ,76.20,77.50,74.65,76.10,76.85,74.20,85864.0,6.526882e+06,2024-01-19,821.0,-0.10,red,2.560647,2.85,-3.508772,1,bearishnews
444,OMINFRAL,BE,139.70,139.70,138.95,138.95,138.95,137.00,42250.0,5.891209e+06,2024-01-19,227.0,-0.75,red,1.423358,0.75,-100.000000,1,bearishnews
515,PFIZER,EQ,4294.90,4294.90,4268.85,4281.60,4280.00,4250.50,55932.0,2.391223e+08,2024-01-19,1370.0,-13.30,red,0.731679,26.05,-51.055662,1,bearishnews
665,REMSONSIND,BE,820.00,820.00,818.00,818.00,818.00,815.00,2466.0,2.021124e+06,2024-01-19,25.0,-2.00,red,0.368098,2.00,-100.000000,1,bearishnews
808,SETFGOLD,EQ,54.82,54.82,54.24,54.51,54.50,54.16,425207.0,2.314586e+07,2024-01-19,1441.0,-0.31,red,0.646233,0.58,-53.448276,1,bearishnews
1104,TCS,EQ,3945.00,3963.55,3915.05,3943.05,3947.00,3902.60,2941975.0,1.159941e+10,2024-01-19,272591.0,-1.95,red,1.036488,48.50,-4.020619,1,bearishnews
1143,TIRUPATIFL,BE,17.10,17.10,17.05,17.05,17.05,16.80,216254.0,3.694646e+06,2024-01-19,699.0,-0.05,red,1.488095,0.05,-100.000000,1,bearishnews
1258,VERTOZ,EQ,796.40,796.40,760.60,773.90,764.80,758.50,485632.0,3.840042e+08,2024-01-19,6192.0,-22.50,red,2.030323,35.80,-62.849162,1,bearishnews
1337,YATHARTH,EQ,379.00,379.75,375.30,378.45,378.50,373.75,155522.0,5.882914e+07,2024-01-19,7173.0,-0.55,red,1.257525,4.45,-12.359551,1,bearishnews

### BULLISH NEWS CANDLE

In [ ]:
# Sort the DataFrame by symbol and date
LTD3.sort_values(['SYMBOL', ' DATE1'], inplace=True)

# Filter stocks with bullish NEWS pattern
filtered_stocks = LTD3.groupby('SYMBOL').apply(lambda x: (x['script'] == 1) & (x[' HIGH_PRICE'] < (x[' LOW_PRICE'].shift())) &
                                                       ((x[' OPEN_PRICE'] - x[' CLOSE_PRICE'])<0))


# Reset index to remove the groupby index
filtered_stocks = filtered_stocks.reset_index(level=0, drop=True)

# Get the names of stocks with news candle pattern
stock_names = filtered_stocks[filtered_stocks].index.unique()

# Print the stock names
# Get the rows based on the indexes
bullishnews = LTD3.loc[stock_names]
bullishnews['TYPE'] = 'bullishnews'
bullishnews.to_csv("bullishnews.csv",index=False)
bullishnews

/var/folders/b1/b6tfvntn1k3cvt9kyzby94gm0000gn/T/ipykernel_16756/2940216959.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  LTD3.sort_values(['SYMBOL', ' DATE1'], inplace=True)

,SYMBOL,SERIES,OPEN_PRICE,HIGH_PRICE,LOW_PRICE,CLOSE_PRICE,LAST_PRICE,PREV_CLOSE,TTL_TRD_QNTY,TRD_VALUE,DATE1,TOTAL_TRADES,BODY,color,Prchng,CANDLE,BODY%,script,TYPE
1497,ADROITINFO,BE,20.40,20.65,20.40,20.65,20.65,29.45,103064.0,2.103926e+06,2024-01-19,399.0,0.25,green,-29.881154,0.25,100.00000,1,bullishnews
2394,IEL,BE,11.90,12.00,11.90,12.00,12.00,12.15,34900.0,4.169555e+05,2024-01-19,105.0,0.10,green,-1.234568,0.10,100.00000,1,bullishnews
238,METROBRAND,EQ,1150.00,1167.50,1140.05,1165.65,1166.50,1213.05,397234.0,4.604602e+08,2024-01-19,28031.0,15.65,green,-3.907506,27.45,57.01275,1,bullishnews
769,SBC,EQ,26.10,28.70,25.50,28.70,28.70,35.90,10128021.0,2.781678e+08,2024-01-19,16505.0,2.60,green,-20.055710,3.20,81.25000,1,bullishnews
921,SICALLOG,BE,275.15,275.20,275.15,275.20,275.20,280.75,54222.0,1.491973e+07,2024-01-19,102.0,0.05,green,-1.976848,0.05,100.00000,1,bullishnews
940,SIMPLEXINF,BE,79.00,80.00,79.00,80.00,80.00,80.30,26054.0,2.063798e+06,2024-01-19,52.0,1.00,green,-0.373599,1.00,100.00000,1,bullishnews

### GAP DOWN BULLISH

In [ ]:
# Sort the DataFrame by symbol and date

LTD3['Candle Color'] = LTD.apply(lambda row: 'Green' if row[' CLOSE_PRICE'] > row[' OPEN_PRICE'] else 'Red', axis=1)
LTD3['% Gap Change'] = (LTD3[' OPEN_PRICE'] - LTD3[' CLOSE_PRICE'].shift(1))*100/LTD3[' CLOSE_PRICE'].shift(1)
LTD3['Body Percent'] = ((LTD3[' CLOSE_PRICE'] - LTD3[' OPEN_PRICE']) / (LTD3[' HIGH_PRICE'] - LTD3[' LOW_PRICE'])) * 100

# Filter stocks with bullish engulfing pattern
filtered_stocks = LTD3.groupby('SYMBOL').apply(lambda x: (x['script'] == 1) &
                                              (x['Body Percent'] > 85) &  # Condition 1: Body Percent > 85%
                                              (x['Candle Color'] == 'Green') &  # Condition 2: Candle is green
                                              (x['% Gap Change'] < -3)
                                              )

# Reset index to remove the groupby index
filtered_stocks = filtered_stocks.reset_index(level=0, drop=True)

# Get the names of stocks with Gap down bullish
stock_names = filtered_stocks[filtered_stocks].index.unique()

# Print the stock names
# Get the rows based on the indexes
gapdown = LTD3.loc[stock_names]
gapdown['TYPE'] = 'gapdown bull'
gapdown.to_csv("gapdownbullish.csv",index=False)
gapdown

/var/folders/b1/b6tfvntn1k3cvt9kyzby94gm0000gn/T/ipykernel_16756/234599406.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  LTD3['Candle Color'] = LTD.apply(lambda row: 'Green' if row[' CLOSE_PRICE'] > row[' OPEN_PRICE'] else 'Red', axis=1)
/var/folders/b1/b6tfvntn1k3cvt9kyzby94gm0000gn/T/ipykernel_16756/234599406.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  LTD3['% Gap Change'] = (LTD3[' OPEN_PRICE'] - LTD3[' CLOSE_PRICE'].shift(1))*100/LTD3[' CLOSE_PRICE'].shift(1)
/var/folders/b1/b6tfvntn1k3cvt9kyzby94gm0000gn/T/ipykernel_16756/234599406.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  LTD3['Body Percent'] = ((LTD3[' CLOSE_PRICE'] - LTD3[' OPEN_PRICE']) / (LTD3[' HIGH_PRICE'] - LTD3[' LOW_PRICE'])) * 100

Empty DataFrame
Columns: [SYMBOL,  SERIES,  OPEN_PRICE,  HIGH_PRICE,  LOW_PRICE,  CLOSE_PRICE,  LAST_PRICE,  PREV_CLOSE,  TTL_TRD_QNTY, TRD_VALUE,  DATE1, TOTAL_TRADES, BODY, color, Prchng, CANDLE, BODY%, script, Candle Color, % Gap Change, Body Percent, TYPE]
Index: []

[0 rows x 22 columns]

In [ ]:
# paired candle strategy
# Sort the DataFrame by symbol and date


# Filter stocks with bullish engulfing pattern
filtered_stocks = LTD3.groupby('SYMBOL').apply(lambda x: (x['script'] == 1) &
                                             (x[' OPEN_PRICE'] <=  x[' CLOSE_PRICE'].shift()) &
                                             (x['BODY'] >=  abs(x['BODY'].shift()))&
                                              ((0.8*x['BODY'])<=  abs(x['BODY'].shift())) &
                                              (abs(x['BODY%'].shift())>=70) &  (x['BODY%']>=70)
                                              & (x[' CLOSE_PRICE']>x[' OPEN_PRICE'].shift())
                                              & ((x[' OPEN_PRICE'].shift()-x[' CLOSE_PRICE'].shift())>0)
                                               &
                                                       ((x[' OPEN_PRICE']-x[' CLOSE_PRICE'])<0)
                                             )

filtered_stocks = filtered_stocks.reset_index(level=0, drop=True)

# Get the names of stocks with news candle pattern
stock_names = filtered_stocks[filtered_stocks].index.unique()



# Print the stock names
# Get the rows based on the indexes
bullpair = LTD3.loc[stock_names]
bullpair['TYPE'] = 'bullpairedcandle'
bullpair.to_csv("bullpairedcandle.csv",index=False)

LTD3.loc[stock_names]
bullpair

Empty DataFrame
Columns: [SYMBOL,  SERIES,  OPEN_PRICE,  HIGH_PRICE,  LOW_PRICE,  CLOSE_PRICE,  LAST_PRICE,  PREV_CLOSE,  TTL_TRD_QNTY, TRD_VALUE,  DATE1, TOTAL_TRADES, BODY, color, Prchng, CANDLE, BODY%, script, Candle Color, % Gap Change, Body Percent, TYPE]
Index: []

[0 rows x 22 columns]

In [ ]:
# paired candle strategy
# Sort the DataFrame by symbol and date


# Filter stocks with bullish engulfing pattern
filtered_stocks = LTD3.groupby('SYMBOL').apply(lambda x: (x['script'] == 1) &
                                             (x[' CLOSE_PRICE'] <  x[' OPEN_PRICE'].shift()) &
                                             (abs(x['BODY'])>=  abs(x['BODY'].shift()))&
                                              ((0.8*abs(x['BODY']))<=  abs(x['BODY'].shift())) &
                                              (abs(x['BODY%'].shift())>=70) &  (abs(x['BODY%'])>=70)
                                              & (x[' OPEN_PRICE']>=x[' CLOSE_PRICE'].shift())
                                              & ((x[' OPEN_PRICE'].shift()-x[' CLOSE_PRICE'].shift())<0)
                                               &((x[' OPEN_PRICE']-x[' CLOSE_PRICE'])>0)
                                             )

filtered_stocks = filtered_stocks.reset_index(level=0, drop=True)

# Get the names of stocks with news candle pattern
stock_names = filtered_stocks[filtered_stocks].index.unique()



# Print the stock names
# Get the rows based on the indexes
bearpair = LTD3.loc[stock_names]
bearpair['TYPE'] = 'bearpairedcandle'
bearpair.to_csv("bearpairedcandle.csv",index=False)

LTD3.loc[stock_names]
bearpair

Empty DataFrame
Columns: [SYMBOL,  SERIES,  OPEN_PRICE,  HIGH_PRICE,  LOW_PRICE,  CLOSE_PRICE,  LAST_PRICE,  PREV_CLOSE,  TTL_TRD_QNTY, TRD_VALUE,  DATE1, TOTAL_TRADES, BODY, color, Prchng, CANDLE, BODY%, script, Candle Color, % Gap Change, Body Percent, TYPE]
Index: []

[0 rows x 22 columns]

In [ ]:
# bullish breakout
# Sort the DataFrame by symbol and date
LTD3['Prchng'] = 100*(LTD3[' CLOSE_PRICE']-LTD3[' PREV_CLOSE'])/LTD3[' PREV_CLOSE']
LTD3['absBODY']=abs(LTD3[' CLOSE_PRICE']-LTD3[' OPEN_PRICE'])
LTD3['Max_Prchng_21_Days'] = LTD3.groupby('SYMBOL')['Prchng'].rolling(window=22, min_periods=2).apply(lambda x: x[:-1].max(), raw=True).reset_index(level=0, drop=True)
LTD3['Min_Prchng_21_Days'] = LTD3.groupby('SYMBOL')['Prchng'].rolling(window=22, min_periods=2).apply(lambda x: x[:-1].min(), raw=True).reset_index(level=0, drop=True)
LTD3['Max_Volume_21_Days'] = LTD3.groupby('SYMBOL')[' TTL_TRD_QNTY'].rolling(window=22, min_periods=2).apply(lambda x: x[:-1].max(), raw=True).reset_index(level=0, drop=True)
LTD3['Max_Body_21_Days'] = LTD3.groupby('SYMBOL')['absBODY'].rolling(window=22, min_periods=2).apply(lambda x: x[:-1].max(), raw=True).reset_index(level=0, drop=True)
LTD3['Max_Prchng_59_Days'] = LTD3.groupby('SYMBOL')['Prchng'].rolling(window=60, min_periods=2).apply(lambda x: x[:-1].max(), raw=True).reset_index(level=0, drop=True)
LTD3['Min_Prchng_59_Days'] = LTD3.groupby('SYMBOL')['Prchng'].rolling(window=60, min_periods=2).apply(lambda x: x[:-1].min(), raw=True).reset_index(level=0, drop=True)
LTD3['Max_Volume_59_Days'] = LTD3.groupby('SYMBOL')[' TTL_TRD_QNTY'].rolling(window=60, min_periods=2).apply(lambda x: x[:-1].max(), raw=True).reset_index(level=0, drop=True)
LTD3['Max_Body_59_Days'] = LTD3.groupby('SYMBOL')['absBODY'].rolling(window=60, min_periods=2).apply(lambda x: x[:-1].max(), raw=True).reset_index(level=0, drop=True)
LTD3['Max_Prchng_251_Days'] = LTD3.groupby('SYMBOL')['Prchng'].rolling(window=252, min_periods=2).apply(lambda x: x[:-1].max(), raw=True).reset_index(level=0, drop=True)
LTD3['Min_Prchng_251_Days'] = LTD3.groupby('SYMBOL')['Prchng'].rolling(window=252, min_periods=2).apply(lambda x: x[:-1].min(), raw=True).reset_index(level=0, drop=True)
LTD3['Max_Volume_251_Days'] = LTD3.groupby('SYMBOL')[' TTL_TRD_QNTY'].rolling(window=252, min_periods=2).apply(lambda x: x[:-1].max(), raw=True).reset_index(level=0, drop=True)
LTD3['Max_Body_251_Days'] = LTD3.groupby('SYMBOL')['absBODY'].rolling(window=252, min_periods=2).apply(lambda x: x[:-1].max(), raw=True).reset_index(level=0, drop=True)
LTD3['Candle Color'] = LTD3.apply(lambda row: 'Green' if row[' CLOSE_PRICE'] > row[' OPEN_PRICE'] else 'Red', axis=1)
LTD3['% Gap Change'] = (LTD3[' OPEN_PRICE'] - LTD3[' CLOSE_PRICE'].shift(1))*100/LTD3[' CLOSE_PRICE'].shift(1)

# Filter stocks with bullish engulfing pattern
filtered_stocks = LTD3.groupby('SYMBOL').apply(lambda x: (x['script'] == 1) &
                                              (x['Prchng'] >  x['Max_Prchng_21_Days'])
                                              & (x[' TTL_TRD_QNTY'] > x['Max_Volume_21_Days'])
                                              & ((x[' CLOSE_PRICE'] - x[' OPEN_PRICE'])> x['Max_Body_21_Days'])
                                              & (x[' CLOSE_PRICE']-x[' OPEN_PRICE']>0)

                                             )

filtered_stocks = filtered_stocks.reset_index(level=0, drop=True)

# Get the names of stocks with news candle pattern
stock_names = filtered_stocks[filtered_stocks].index.unique()



# Print the stock names
# Get the rows based on the indexes
bullishbreakout = LTD3.loc[stock_names]
bullishbreakout['TYPE'] = 'Bullish MPVB'
bullishbreakout.to_csv("mbullishbreakout.csv",index=False)
LTD3.loc[stock_names]
bullishbreakout

/var/folders/b1/b6tfvntn1k3cvt9kyzby94gm0000gn/T/ipykernel_16756/3983072762.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  LTD3['Prchng'] = 100*(LTD3[' CLOSE_PRICE']-LTD3[' PREV_CLOSE'])/LTD3[' PREV_CLOSE']
/var/folders/b1/b6tfvntn1k3cvt9kyzby94gm0000gn/T/ipykernel_16756/3983072762.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  LTD3['absBODY']=abs(LTD3[' CLOSE_PRICE']-LTD3[' OPEN_PRICE'])
/var/folders/b1/b6tfvntn1k3cvt9kyzby94gm0000gn/T/ipykernel_16756/3983072762.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  LTD3['Max_Prchng_21_Days'] = LTD3.groupby('SYMBOL')['Prchng'].rolling(window=22, min_periods=2).apply(lambda x: x[:-1].max(), raw=True).reset_index(level=0, drop=True)
/var/folders/b1/b6tfvntn1k3cvt9kyzby94gm0000gn/T/ipykernel_16756/3983072762.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  LTD3['Min_Prchng_21_Days'] = LTD3.groupby('SYMBOL')['Prchng'].rolling(window=22, min_periods=2).apply(lambda x: x[:-1].min(), raw=True).reset_index(level=0, drop=True)
/var/folders/b1/b6tfvntn1k3cvt9kyzby94gm0000gn/T/ipykernel_16756/3983072762.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  LTD3['Max_Volume_21_Days'] = LTD3.groupby('SYMBOL')[' TTL_TRD_QNTY'].rolling(window=22, min_periods=2).apply(lambda x: x[:-1].max(), raw=True).reset_index(level=0, drop=True)
/var/folders/b1/b6tfvntn1k3cvt9kyzby94gm0000gn/T/ipykernel_16756/3983072762.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  LTD3['Max_Body_21_Days'] = LTD3.groupby('SYMBOL')['absBODY'].rolling(window=22, min_periods=2).apply(lambda x: x[:-1].max(), raw=True).reset_index(level=0, drop=True)
/var/folders/b1/b6tfvntn1k3cvt9kyzby94gm0000gn/T/ipykernel_16756/3983072762.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  LTD3['Max_Prchng_59_Days'] = LTD3.groupby('SYMBOL')['Prchng'].rolling(window=60, min_periods=2).apply(lambda x: x[:-1].max(), raw=True).reset_index(level=0, drop=True)
/var/folders/b1/b6tfvntn1k3cvt9kyzby94gm0000gn/T/ipykernel_16756/3983072762.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  LTD3['Min_Prchng_59_Days'] = LTD3.groupby('SYMBOL')['Prchng'].rolling(window=60, min_periods=2).apply(lambda x: x[:-1].min(), raw=True).reset_index(level=0, drop=True)
/var/folders/b1/b6tfvntn1k3cvt9kyzby94gm0000gn/T/ipykernel_16756/3983072762.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  LTD3['Max_Volume_59_Days'] = LTD3.groupby('SYMBOL')[' TTL_TRD_QNTY'].rolling(window=60, min_periods=2).apply(lambda x: x[:-1].max(), raw=True).reset_index(level=0, drop=True)
/var/folders/b1/b6tfvntn1k3cvt9kyzby94gm0000gn/T/ipykernel_16756/3983072762.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  LTD3['Max_Body_59_Days'] = LTD3.groupby('SYMBOL')['absBODY'].rolling(window=60, min_periods=2).apply(lambda x: x[:-1].max(), raw=True).reset_index(level=0, drop=True)
/var/folders/b1/b6tfvntn1k3cvt9kyzby94gm0000gn/T/ipykernel_16756/3983072762.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  LTD3['Max_Prchng_251_Days'] = LTD3.groupby('SYMBOL')['Prchng'].rolling(window=252, min_periods=2).apply(lambda x: x[:-1].max(), raw=True).reset_index(level=0, drop=True)
/var/folders/b1/b6tfvntn1k3cvt9kyzby94gm0000gn/T/ipykernel_16756/3983072762.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  LTD3['Min_Prchng_251_Days'] = LTD3.groupby('SYMBOL')['Prchng'].rolling(window=252, min_periods=2).apply(lambda x: x[:-1].min(), raw=True).reset_index(level=0, drop=True)
/var/folders/b1/b6tfvntn1k3cvt9kyzby94gm0000gn/T/ipykernel_16756/3983072762.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  LTD3['Max_Volume_251_Days'] = LTD3.groupby('SYMBOL')[' TTL_TRD_QNTY'].rolling(window=252, min_periods=2).apply(lambda x: x[:-1].max(), raw=True).reset_index(level=0, drop=True)
/var/folders/b1/b6tfvntn1k3cvt9kyzby94gm0000gn/T/ipykernel_16756/3983072762.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  LTD3['Max_Body_251_Days'] = LTD3.groupby('SYMBOL')['absBODY'].rolling(window=252, min_periods=2).apply(lambda x: x[:-1].max(), raw=True).reset_index(level=0, drop=True)
/var/folders/b1/b6tfvntn1k3cvt9kyzby94gm0000gn/T/ipykernel_16756/3983072762.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  LTD3['Candle Color'] = LTD3.apply(lambda row: 'Green' if row[' CLOSE_PRICE'] > row[' OPEN_PRICE'] else 'Red', axis=1)
/var/folders/b1/b6tfvntn1k3cvt9kyzby94gm0000gn/T/ipykernel_16756/3983072762.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  LTD3['% Gap Change'] = (LTD3[' OPEN_PRICE'] - LTD3[' CLOSE_PRICE'].shift(1))*100/LTD3[' CLOSE_PRICE'].shift(1)

,SYMBOL,SERIES,OPEN_PRICE,HIGH_PRICE,LOW_PRICE,CLOSE_PRICE,LAST_PRICE,PREV_CLOSE,TTL_TRD_QNTY,TRD_VALUE,...,Max_Body_21_Days,Max_Prchng_59_Days,Min_Prchng_59_Days,Max_Volume_59_Days,Max_Body_59_Days,Max_Prchng_251_Days,Min_Prchng_251_Days,Max_Volume_251_Days,Max_Body_251_Days,TYPE
1456,AARTIIND,EQ,617.45,691.75,614.80,678.90,675.00,611.60,15007983.0,9.920103e+09,...,39.05,10.737162,-5.797339,14781664.0,39.05,10.737162,-8.964465,14781664.0,54.55,Bullish MPVB
1535,ALBERTDAVD,EQ,1089.95,1259.00,1064.10,1236.20,1224.90,1080.65,133422.0,1.600017e+08,...,51.30,6.172387,-4.361018,144692.0,51.30,6.485096,-4.361018,152149.0,76.40,Bullish MPVB
1582,APOLLOPIPE,EQ,682.00,750.00,679.60,728.80,733.00,679.95,642394.0,4.677842e+08,...,23.80,3.659482,-2.608882,196092.0,27.75,10.174255,-5.441109,546558.0,49.00,Bullish MPVB
1634,ATAM,EQ,205.55,218.00,204.35,218.00,218.00,207.65,123312.0,2.652870e+07,...,11.40,9.990890,-5.278311,268256.0,20.50,16.202761,-6.523856,268256.0,26.00,Bullish MPVB
1687,BAJAJHLDNG,EQ,8003.50,8500.00,8003.50,8472.80,8450.00,7999.35,135675.0,1.134242e+09,...,273.45,7.051098,-4.273566,157847.0,453.30,7.051098,-4.273566,428643.0,453.30,Bullish MPVB
1747,BHARTIARTL,EQ,1091.00,1136.35,1089.80,1125.00,1123.00,1087.05,11753391.0,1.316687e+10,...,24.35,2.420216,-2.386646,13805235.0,24.35,3.842629,-2.582657,47342125.0,30.90,Bullish MPVB
1761,BLBLIMITED,EQ,24.00,26.80,23.65,26.80,26.80,22.35,7724210.0,1.930889e+08,...,1.80,6.372549,-6.329114,5920491.0,1.80,9.951456,-9.397163,5920491.0,3.25,Bullish MPVB
1883,CORDSCABLE,EQ,113.30,122.00,112.80,121.10,120.70,113.25,185725.0,2.211721e+07,...,6.20,7.863636,-5.659556,948006.0,8.45,15.636588,-9.192922,3239404.0,14.00,Bullish MPVB
2047,EMAMIPAP,EQ,120.45,133.50,120.00,132.35,132.60,119.80,1111895.0,1.444723e+08,...,5.35,3.240741,-3.917221,253415.0,5.40,9.097716,-9.955827,422610.0,14.60,Bullish MPVB
2100,FILATEX,EQ,54.40,59.35,53.85,57.45,57.70,53.75,22994821.0,1.311345e+09,...,1.70,9.617373,-6.048387,11755695.0,4.35,10.678392,-7.260407,11755695.0,4.35,Bullish MPVB
2154,GICHSGFIN,EQ,241.50,268.05,241.50,262.70,264.00,239.70,3579017.0,9.274641e+08,...,15.85,6.771110,-7.604657,3812701.0,15.85,7.241469,-11.645508,3812701.0,15.85,Bullish MPVB
2156,GICRE,EQ,307.50,363.95,307.50,356.05,355.70,305.70,14982293.0,5.118355e+09,...,19.85,16.458096,-5.432596,24375853.0,43.40,19.469599,-12.408363,24375853.0,43.40,Bullish MPVB
2317,HIRECT,EQ,554.90,604.55,554.90,600.90,604.55,549.60,57296.0,3.385539e+07,...,32.25,19.993938,-9.167586,283041.0,95.00,19.993938,-9.167586,444798.0,95.00,Bullish MPVB
2336,HPAL,EQ,99.00,117.45,98.30,115.35,117.40,97.90,6432467.0,7.106266e+08,...,6.35,7.660021,-80.230287,2718413.0,18.45,9.061005,-80.230287,2718413.0,32.95,Bullish MPVB
2488,INTELLECT,EQ,870.00,956.30,870.00,923.75,925.00,866.20,3767825.0,3.490718e+09,...,30.80,5.480090,-3.401829,1964070.0,49.45,19.698545,-5.814384,16495461.0,86.40,Bullish MPVB
2500,IRCON,EQ,204.70,230.85,204.65,227.80,227.70,204.05,104577928.0,2.306980e+10,...,15.05,8.373747,-7.861991,86311747.0,15.05,19.977553,-7.861991,100253919.0,19.05,Bullish MPVB
28,KMSUGAR,EQ,30.40,32.55,30.40,32.05,32.05,30.15,1006762.0,3.201781e+07,...,1.40,5.981595,-5.162242,2065468.0,1.65,13.090129,-8.139535,9726724.0,3.20,Bullish MPVB
104,LIBERTSHOE,EQ,335.90,399.35,333.50,368.85,368.00,332.80,3614991.0,1.355862e+09,...,26.90,10.587038,-6.334063,1799101.0,26.90,20.000000,-9.991725,3712389.0,42.50,Bullish MPVB
115,LINDEINDIA,EQ,5454.95,5985.00,5417.75,5822.25,5830.00,5410.45,330151.0,1.919424e+09,...,215.85,3.605541,-2.709549,772960.0,215.85,13.797821,-6.506143,1051166.0,769.10,Bullish MPVB
260,MITCON,EQ,113.00,133.65,111.40,133.65,133.65,111.40,943511.0,1.220598e+08,...,12.05,16.063596,-6.435006,538183.0,12.05,16.063596,-7.250163,1014973.0,12.05,Bullish MPVB
328,NAHARPOLY,EQ,224.60,240.00,224.10,238.65,240.00,224.10,127131.0,2.987983e+07,...,8.65,4.719699,-3.711067,80974.0,8.65,13.263666,-9.339170,538354.0,31.35,Bullish MPVB
329,NAHARSPING,EQ,275.55,318.65,275.55,302.70,303.80,275.00,755556.0,2.295509e+08,...,10.15,9.879816,-3.065384,1177531.0,26.15,13.916756,-7.677785,1177531.0,29.90,Bullish MPVB
384,NIACL,EQ,223.00,243.30,222.50,242.90,243.30,221.20,7328949.0,1.743828e+09,...,13.35,19.977038,-9.384796,50665997.0,33.00,19.977038,-9.384796,50665997.0,33.00,Bullish MPVB
464,ORIENTPPR,EQ,48.45,54.90,48.15,54.00,53.80,48.05,24952805.0,1.315086e+09,...,2.75,6.152125,-7.799145,12986090.0,3.90,15.711462,-10.139165,19524536.0,7.75,Bullish MPVB
473,PAKKA,EQ,330.00,378.90,328.05,371.25,371.00,323.35,2192409.0,7.805178e+08,...,37.00,13.371519,-5.020747,2146497.0,37.00,19.990788,-17.941953,3343652.0,41.15,Bullish MPVB
574,PRIMESECU,EQ,181.80,201.60,172.20,190.00,186.00,178.35,274152.0,5.200216e+07,...,8.05,4.274722,-4.391434,311312.0,8.05,6.236559,-6.160991,589073.0,12.95,Bullish MPVB
713,RUCHIRA,EQ,137.95,153.00,137.95,146.40,147.00,136.75,997116.0,1.469640e+08,...,4.15,3.780342,-5.263158,887782.0,7.85,10.557342,-8.581197,1579199.0,11.50,Bullish MPVB
718,RVNL,EQ,245.75,292.30,245.00,291.25,292.30,243.60,178930889.0,4.899137e+10,...,17.00,8.560886,-6.391080,136773825.0,17.00,19.202279,-10.369393,395800528.0,26.65,Bullish MPVB
1145,TITAN,EQ,3742.20,3861.50,3740.70,3810.60,3816.00,3734.70,2566367.0,9.730785e+09,...,63.95,2.348826,-2.730681,1562141.0,70.05,6.715480,-3.131361,3693638.0,143.00,Bullish MPVB
1225,USHAMART,EQ,311.00,347.60,310.20,340.50,338.90,308.55,5058063.0,1.696399e+09,...,15.40,5.991364,-6.475635,2694531.0,20.15,7.873546,-8.849558,7406368.0,21.75,Bullish MPVB
1294,VOLTAMP,EQ,7045.00,8112.15,7045.00,7586.40,7600.00,7067.55,198288.0,1.521364e+09,...,516.25,8.961933,-6.875979,216320.0,516.25,15.132371,-8.760366,551007.0,516.25,Bullish MPVB

In [ ]:
# bullish breakout
# Sort the DataFrame by symbol and date


# Filter stocks with bullish engulfing pattern
filtered_stocks = LTD3.groupby('SYMBOL').apply(lambda x: (x['script'] == 1) &
                                              (x['Prchng'] >  x['Max_Prchng_59_Days'])
                                              & (x[' TTL_TRD_QNTY'] > x['Max_Volume_59_Days'])
                                              & ((x[' CLOSE_PRICE'] - x[' OPEN_PRICE'])> x['Max_Body_59_Days'])
                                              & (x[' CLOSE_PRICE']-x[' OPEN_PRICE']>0)

                                             )

filtered_stocks = filtered_stocks.reset_index(level=0, drop=True)

# Get the names of stocks with news candle pattern
stock_names = filtered_stocks[filtered_stocks].index.unique()



# Print the stock names
# Get the rows based on the indexes
bullishbreakout = LTD3.loc[stock_names]
bullishbreakout['TYPE'] = 'Bullish QPVB'
bullishbreakout.to_csv("qbullishbreakout.csv",index=False)
LTD3.loc[stock_names]
bullishbreakout

,SYMBOL,SERIES,OPEN_PRICE,HIGH_PRICE,LOW_PRICE,CLOSE_PRICE,LAST_PRICE,PREV_CLOSE,TTL_TRD_QNTY,TRD_VALUE,...,Max_Body_21_Days,Max_Prchng_59_Days,Min_Prchng_59_Days,Max_Volume_59_Days,Max_Body_59_Days,Max_Prchng_251_Days,Min_Prchng_251_Days,Max_Volume_251_Days,Max_Body_251_Days,TYPE
1456,AARTIIND,EQ,617.45,691.75,614.80,678.90,675.00,611.60,15007983.0,9.920103e+09,...,39.05,10.737162,-5.797339,14781664.0,39.05,10.737162,-8.964465,14781664.0,54.55,Bullish QPVB
1582,APOLLOPIPE,EQ,682.00,750.00,679.60,728.80,733.00,679.95,642394.0,4.677842e+08,...,23.80,3.659482,-2.608882,196092.0,27.75,10.174255,-5.441109,546558.0,49.00,Bullish QPVB
1761,BLBLIMITED,EQ,24.00,26.80,23.65,26.80,26.80,22.35,7724210.0,1.930889e+08,...,1.80,6.372549,-6.329114,5920491.0,1.80,9.951456,-9.397163,5920491.0,3.25,Bullish QPVB
2047,EMAMIPAP,EQ,120.45,133.50,120.00,132.35,132.60,119.80,1111895.0,1.444723e+08,...,5.35,3.240741,-3.917221,253415.0,5.40,9.097716,-9.955827,422610.0,14.60,Bullish QPVB
2488,INTELLECT,EQ,870.00,956.30,870.00,923.75,925.00,866.20,3767825.0,3.490718e+09,...,30.80,5.480090,-3.401829,1964070.0,49.45,19.698545,-5.814384,16495461.0,86.40,Bullish QPVB
2500,IRCON,EQ,204.70,230.85,204.65,227.80,227.70,204.05,104577928.0,2.306980e+10,...,15.05,8.373747,-7.861991,86311747.0,15.05,19.977553,-7.861991,100253919.0,19.05,Bullish QPVB
104,LIBERTSHOE,EQ,335.90,399.35,333.50,368.85,368.00,332.80,3614991.0,1.355862e+09,...,26.90,10.587038,-6.334063,1799101.0,26.90,20.000000,-9.991725,3712389.0,42.50,Bullish QPVB
260,MITCON,EQ,113.00,133.65,111.40,133.65,133.65,111.40,943511.0,1.220598e+08,...,12.05,16.063596,-6.435006,538183.0,12.05,16.063596,-7.250163,1014973.0,12.05,Bullish QPVB
328,NAHARPOLY,EQ,224.60,240.00,224.10,238.65,240.00,224.10,127131.0,2.987983e+07,...,8.65,4.719699,-3.711067,80974.0,8.65,13.263666,-9.339170,538354.0,31.35,Bullish QPVB
464,ORIENTPPR,EQ,48.45,54.90,48.15,54.00,53.80,48.05,24952805.0,1.315086e+09,...,2.75,6.152125,-7.799145,12986090.0,3.90,15.711462,-10.139165,19524536.0,7.75,Bullish QPVB
473,PAKKA,EQ,330.00,378.90,328.05,371.25,371.00,323.35,2192409.0,7.805178e+08,...,37.00,13.371519,-5.020747,2146497.0,37.00,19.990788,-17.941953,3343652.0,41.15,Bullish QPVB
713,RUCHIRA,EQ,137.95,153.00,137.95,146.40,147.00,136.75,997116.0,1.469640e+08,...,4.15,3.780342,-5.263158,887782.0,7.85,10.557342,-8.581197,1579199.0,11.50,Bullish QPVB
718,RVNL,EQ,245.75,292.30,245.00,291.25,292.30,243.60,178930889.0,4.899137e+10,...,17.00,8.560886,-6.391080,136773825.0,17.00,19.202279,-10.369393,395800528.0,26.65,Bullish QPVB
1225,USHAMART,EQ,311.00,347.60,310.20,340.50,338.90,308.55,5058063.0,1.696399e+09,...,15.40,5.991364,-6.475635,2694531.0,20.15,7.873546,-8.849558,7406368.0,21.75,Bullish QPVB

In [ ]:
# bullish breakout
# Sort the DataFrame by symbol and date


# Filter stocks with bullish engulfing pattern
filtered_stocks = LTD3.groupby('SYMBOL').apply(lambda x: (x['script'] == 1) &
                                              (x['Prchng'] >  x['Max_Prchng_251_Days'])
                                              & (x[' TTL_TRD_QNTY'] > x['Max_Volume_251_Days'])
                                              & ((x[' CLOSE_PRICE'] - x[' OPEN_PRICE'])> x['Max_Body_251_Days'])
                                              & (x[' CLOSE_PRICE']-x[' OPEN_PRICE']>0)

                                             )

filtered_stocks = filtered_stocks.reset_index(level=0, drop=True)

# Get the names of stocks with news candle pattern
stock_names = filtered_stocks[filtered_stocks].index.unique()



# Print the stock names
# Get the rows based on the indexes
bullishbreakout = LTD3.loc[stock_names]
bullishbreakout['TYPE'] = 'Bullish YPVB'
bullishbreakout.to_csv("ybullishbreakout.csv",index=False)
LTD3.loc[stock_names]
bullishbreakout

,SYMBOL,SERIES,OPEN_PRICE,HIGH_PRICE,LOW_PRICE,CLOSE_PRICE,LAST_PRICE,PREV_CLOSE,TTL_TRD_QNTY,TRD_VALUE,...,Max_Body_21_Days,Max_Prchng_59_Days,Min_Prchng_59_Days,Max_Volume_59_Days,Max_Body_59_Days,Max_Prchng_251_Days,Min_Prchng_251_Days,Max_Volume_251_Days,Max_Body_251_Days,TYPE
1456,AARTIIND,EQ,617.45,691.75,614.8,678.9,675.0,611.6,15007983.0,9.920103e+09,...,39.05,10.737162,-5.797339,14781664.0,39.05,10.737162,-8.964465,14781664.0,54.55,Bullish YPVB

In [ ]:
# bearish breakout
# Sort the DataFrame by symbol and date


# Filter stocks with bullish engulfing pattern
filtered_stocks = LTD3.groupby('SYMBOL').apply(lambda x: (x['script'] == 1) &
                                              (x['Prchng'] < x['Min_Prchng_21_Days'])
                                              & (x[' TTL_TRD_QNTY'] > x['Max_Volume_21_Days'])
                                              & ((x[' OPEN_PRICE'] - x[' CLOSE_PRICE'])> x['Max_Body_21_Days'])
                                              & (x[' CLOSE_PRICE']-x[' OPEN_PRICE']<0)

                                             )

filtered_stocks = filtered_stocks.reset_index(level=0, drop=True)

# Get the names of stocks with news candle pattern
stock_names = filtered_stocks[filtered_stocks].index.unique()



# Print the stock names
# Get the rows based on the indexes
bearishbreakout = LTD3.loc[stock_names]
bearishbreakout['TYPE'] = 'bearish MPVB'
bearishbreakout.to_csv("mbearishbreakout.csv",index=False)

LTD3.loc[stock_names]
bearishbreakout

,SYMBOL,SERIES,OPEN_PRICE,HIGH_PRICE,LOW_PRICE,CLOSE_PRICE,LAST_PRICE,PREV_CLOSE,TTL_TRD_QNTY,TRD_VALUE,...,Max_Body_21_Days,Max_Prchng_59_Days,Min_Prchng_59_Days,Max_Volume_59_Days,Max_Body_59_Days,Max_Prchng_251_Days,Min_Prchng_251_Days,Max_Volume_251_Days,Max_Body_251_Days,TYPE
2468,INDUSINDBK,EQ,1622.7,1631.75,1550.2,1561.1,1560.5,1612.9,10982524.0,1.726784e+10,...,55.55,3.668595,-2.10712,45549217.0,55.55,4.9427,-7.398672,45549217.0,64.6,bearish MPVB

In [ ]:
# bearish breakout
# Sort the DataFrame by symbol and date


# Filter stocks with bullish engulfing pattern
filtered_stocks = LTD3.groupby('SYMBOL').apply(lambda x: (x['script'] == 1) &
                                              (x['Prchng'] < x['Min_Prchng_59_Days'])
                                              & (x[' TTL_TRD_QNTY'] > x['Max_Volume_59_Days'])
                                              & ((x[' OPEN_PRICE'] - x[' CLOSE_PRICE'])> x['Max_Body_59_Days'])
                                              & (x[' CLOSE_PRICE']-x[' OPEN_PRICE']<0)

                                             )

filtered_stocks = filtered_stocks.reset_index(level=0, drop=True)

# Get the names of stocks with news candle pattern
stock_names = filtered_stocks[filtered_stocks].index.unique()



# Print the stock names
# Get the rows based on the indexes
bearishbreakout = LTD3.loc[stock_names]
bearishbreakout['TYPE'] = 'bearish QPVB'
bearishbreakout.to_csv("qbearishbreakout.csv",index=False)

LTD3.loc[stock_names]

Empty DataFrame
Columns: [SYMBOL,  SERIES,  OPEN_PRICE,  HIGH_PRICE,  LOW_PRICE,  CLOSE_PRICE,  LAST_PRICE,  PREV_CLOSE,  TTL_TRD_QNTY, TRD_VALUE,  DATE1, TOTAL_TRADES, BODY, color, Prchng, CANDLE, BODY%, script, Candle Color, % Gap Change, Body Percent, absBODY, Max_Prchng_21_Days, Min_Prchng_21_Days, Max_Volume_21_Days, Max_Body_21_Days, Max_Prchng_59_Days, Min_Prchng_59_Days, Max_Volume_59_Days, Max_Body_59_Days, Max_Prchng_251_Days, Min_Prchng_251_Days, Max_Volume_251_Days, Max_Body_251_Days]
Index: []

[0 rows x 34 columns]

In [ ]:
# bearish breakout
# Sort the DataFrame by symbol and date


# Filter stocks with bullish engulfing pattern
filtered_stocks = LTD3.groupby('SYMBOL').apply(lambda x: (x['script'] == 1) &
                                              (x['Prchng'] < x['Min_Prchng_251_Days'])
                                              & (x[' TTL_TRD_QNTY'] > x['Max_Volume_251_Days'])
                                              & ((x[' OPEN_PRICE'] - x[' CLOSE_PRICE'])> x['Max_Body_251_Days'])
                                              & (x[' CLOSE_PRICE']-x[' OPEN_PRICE']<0)

                                             )

filtered_stocks = filtered_stocks.reset_index(level=0, drop=True)

# Get the names of stocks with news candle pattern
stock_names = filtered_stocks[filtered_stocks].index.unique()



# Print the stock names
# Get the rows based on the indexes
bearishbreakout = LTD3.loc[stock_names]
bearishbreakout['TYPE'] = 'bearish YPVB'
bearishbreakout.to_csv("ybearishbreakout.csv",index=False)

LTD3.loc[stock_names]

Empty DataFrame
Columns: [SYMBOL,  SERIES,  OPEN_PRICE,  HIGH_PRICE,  LOW_PRICE,  CLOSE_PRICE,  LAST_PRICE,  PREV_CLOSE,  TTL_TRD_QNTY, TRD_VALUE,  DATE1, TOTAL_TRADES, BODY, color, Prchng, CANDLE, BODY%, script, Candle Color, % Gap Change, Body Percent, absBODY, Max_Prchng_21_Days, Min_Prchng_21_Days, Max_Volume_21_Days, Max_Body_21_Days, Max_Prchng_59_Days, Min_Prchng_59_Days, Max_Volume_59_Days, Max_Body_59_Days, Max_Prchng_251_Days, Min_Prchng_251_Days, Max_Volume_251_Days, Max_Body_251_Days]
Index: []

[0 rows x 34 columns]

### PcvsTC

In [ ]:
LTD3['PcvsTC'] = LTD3.apply(lambda row: 1 if (row[' DATE1'].date() == latest_date and row['Prchng'] > 0) else 0, axis=1)

/var/folders/b1/b6tfvntn1k3cvt9kyzby94gm0000gn/T/ipykernel_16756/1867794934.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  LTD3['PcvsTC'] = LTD3.apply(lambda row: 1 if (row[' DATE1'].date() == latest_date and row['Prchng'] > 0) else 0, axis=1)

In [ ]:
def compare_open_low(group):
    # Check if the script is 1
    if (group['script'] == 1).any():
        # Get the open price value for script 1
        open_price_script_1 = group.loc[group['script'] == 1, ' OPEN_PRICE'].values[0]
        # Check if the script is 0
        if (group['script'] == 0).any():
            # Get the low price value for script 0
            low_price_script_0 = group.loc[group['script'] == 0, ' LOW_PRICE'].values[0]
            # Compare open_price_script_1 with low_price_script_0 and assign the result
            group['Lowcheck'] = (group['script'] == 1) & (open_price_script_1 > low_price_script_0)
        else:
            # No script 0, assign 0 to all rows
            group['Lowcheck'] = 0
    else:
        # No script 1, assign 0 to all rows
        group['Lowcheck'] = 0
    return group

LTD3['Lowcheck'] = LTD3.groupby('SYMBOL').apply(compare_open_low)['Lowcheck']

/var/folders/b1/b6tfvntn1k3cvt9kyzby94gm0000gn/T/ipykernel_16756/3752291681.py:20: FutureWarning: Not prepending group keys to the result index of transform-like apply. In the future, the group keys will be included in the index, regardless of whether the applied function returns a like-indexed object.
To preserve the previous behavior, use

	>>> .groupby(..., group_keys=False)

To adopt the future behavior and silence this warning, use

	>>> .groupby(..., group_keys=True)
  LTD3['Lowcheck'] = LTD3.groupby('SYMBOL').apply(compare_open_low)['Lowcheck']
/var/folders/b1/b6tfvntn1k3cvt9kyzby94gm0000gn/T/ipykernel_16756/3752291681.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  LTD3['Lowcheck'] = LTD3.groupby('SYMBOL').apply(compare_open_low)['Lowcheck']

In [ ]:
def compare_close_high(group):
    # Check if the script is 1
    if (group['script'] == 1).any():
        # Get the close price value for script 1
        close_price_script_1 = group.loc[group['script'] == 1, ' CLOSE_PRICE'].values[0]
        # Check if the script is 0
        if (group['script'] == 0).any():
            # Get the high price value for script 0
            high_price_script_0 = group.loc[group['script'] == 0, ' HIGH_PRICE'].values[0]
            # Compare close_price_script_1 with high_price_script_0 and assign the result
            group['highcheck'] = (group['script'] == 1) & (close_price_script_1 > high_price_script_0)
        else:
            # No script 0, assign 0 to all rows
            group['highcheck'] = 0
    else:
        # No script 1, assign 0 to all rows
        group['highcheck'] = 0
    return group

LTD3['highcheck'] = LTD3.groupby('SYMBOL').apply(compare_close_high)['highcheck']

/var/folders/b1/b6tfvntn1k3cvt9kyzby94gm0000gn/T/ipykernel_16756/1377794489.py:20: FutureWarning: Not prepending group keys to the result index of transform-like apply. In the future, the group keys will be included in the index, regardless of whether the applied function returns a like-indexed object.
To preserve the previous behavior, use

	>>> .groupby(..., group_keys=False)

To adopt the future behavior and silence this warning, use

	>>> .groupby(..., group_keys=True)
  LTD3['highcheck'] = LTD3.groupby('SYMBOL').apply(compare_close_high)['highcheck']
/var/folders/b1/b6tfvntn1k3cvt9kyzby94gm0000gn/T/ipykernel_16756/1377794489.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  LTD3['highcheck'] = LTD3.groupby('SYMBOL').apply(compare_close_high)['highcheck']

In [ ]:
def compare_prchng_zero(group):
    # Check if the script is 0
    if (group['script'] == 0).any():
        # Check if Prchng is less than zero for script 0
        prchng_script_0 = group.loc[group['script'] == 0, 'Prchng'].values[0]
        group['prevClose'] = (group['script'] == 1) & (prchng_script_0 < 0)
    else:
        # No script 0, assign 0 to all rows
        group['prevClose'] = 0
    return group

LTD3['prevClose'] = LTD3.groupby('SYMBOL').apply(compare_prchng_zero)['prevClose']

/var/folders/b1/b6tfvntn1k3cvt9kyzby94gm0000gn/T/ipykernel_16756/3159113915.py:12: FutureWarning: Not prepending group keys to the result index of transform-like apply. In the future, the group keys will be included in the index, regardless of whether the applied function returns a like-indexed object.
To preserve the previous behavior, use

	>>> .groupby(..., group_keys=False)

To adopt the future behavior and silence this warning, use

	>>> .groupby(..., group_keys=True)
  LTD3['prevClose'] = LTD3.groupby('SYMBOL').apply(compare_prchng_zero)['prevClose']
/var/folders/b1/b6tfvntn1k3cvt9kyzby94gm0000gn/T/ipykernel_16756/3159113915.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  LTD3['prevClose'] = LTD3.groupby('SYMBOL').apply(compare_prchng_zero)['prevClose']

## COMBINING RESULTS

In [ ]:
# List of CSV files to combine
csv_files = ["bullengulfing.csv", "bearengulfing.csv", "bullishnews.csv", "bearishnews.csv", "ltp_cp.csv", "threewhitesoldiers.csv", "threeblackcrows.csv", "W.csv", "M.csv","bullpairedcandle.csv","bearpairedcandle.csv","mbullishbreakout.csv","mbearishbreakout.csv","qbullishbreakout.csv","qbearishbreakout.csv","ybullishbreakout.csv","ybearishbreakout.csv","gapdownbullish.csv"]

# Output file to save the combined data
output_file = "combined_data.csv"

# Desired column names to keep in the final CSV
columns_to_keep = [" DATE1", "TYPE", " SERIES", "SYMBOL", " CLOSE_PRICE", "color", "Prchng"," LOW_PRICE"," HIGH_PRICE"]

# Create a set to store all unique column names from all CSV files
all_columns = set()

# Loop through each CSV file and collect unique column names
for file in csv_files:
    data = pd.read_csv(file, nrows=0)
    all_columns.update(data.columns)

# Find the common columns present in all CSV files and keep only the desired columns
common_columns = list(all_columns.intersection(columns_to_keep))

# Create an empty DataFrame to store the combined data
combined_data = pd.DataFrame()

# Loop through each CSV file and concatenate them into the combined_data DataFrame
for file in csv_files:
    data = pd.read_csv(file, usecols=common_columns)
    combined_data = combined_data.append(data, ignore_index=True)

# Save the combined data to the output_file
combined_data.to_csv(output_file, index=False)
print(f"Combined data with specific columns saved to {output_file}")

Combined data with specific columns saved to combined_data.csv

/var/folders/b1/b6tfvntn1k3cvt9kyzby94gm0000gn/T/ipykernel_16756/2517942668.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  combined_data = combined_data.append(data, ignore_index=True)
/var/folders/b1/b6tfvntn1k3cvt9kyzby94gm0000gn/T/ipykernel_16756/2517942668.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  combined_data = combined_data.append(data, ignore_index=True)
/var/folders/b1/b6tfvntn1k3cvt9kyzby94gm0000gn/T/ipykernel_16756/2517942668.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  combined_data = combined_data.append(data, ignore_index=True)
/var/folders/b1/b6tfvntn1k3cvt9kyzby94gm0000gn/T/ipykernel_16756/2517942668.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  combined_data = combined_data.append(data, ignore_index=True)
/var/folders/b1/b6tfvntn1k3cvt9kyzby94gm0000gn/T/ipykernel_16756/2517942668.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  combined_data = combined_data.append(data, ignore_index=True)
/var/folders/b1/b6tfvntn1k3cvt9kyzby94gm0000gn/T/ipykernel_16756/2517942668.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  combined_data = combined_data.append(data, ignore_index=True)
/var/folders/b1/b6tfvntn1k3cvt9kyzby94gm0000gn/T/ipykernel_16756/2517942668.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  combined_data = combined_data.append(data, ignore_index=True)
/var/folders/b1/b6tfvntn1k3cvt9kyzby94gm0000gn/T/ipykernel_16756/2517942668.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  combined_data = combined_data.append(data, ignore_index=True)
/var/folders/b1/b6tfvntn1k3cvt9kyzby94gm0000gn/T/ipykernel_16756/2517942668.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  combined_data = combined_data.append(data, ignore_index=True)
/var/folders/b1/b6tfvntn1k3cvt9kyzby94gm0000gn/T/ipykernel_16756/2517942668.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  combined_data = combined_data.append(data, ignore_index=True)
/var/folders/b1/b6tfvntn1k3cvt9kyzby94gm0000gn/T/ipykernel_16756/2517942668.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  combined_data = combined_data.append(data, ignore_index=True)
/var/folders/b1/b6tfvntn1k3cvt9kyzby94gm0000gn/T/ipykernel_16756/2517942668.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  combined_data = combined_data.append(data, ignore_index=True)
/var/folders/b1/b6tfvntn1k3cvt9kyzby94gm0000gn/T/ipykernel_16756/2517942668.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  combined_data = combined_data.append(data, ignore_index=True)
/var/folders/b1/b6tfvntn1k3cvt9kyzby94gm0000gn/T/ipykernel_16756/2517942668.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  combined_data = combined_data.append(data, ignore_index=True)
/var/folders/b1/b6tfvntn1k3cvt9kyzby94gm0000gn/T/ipykernel_16756/2517942668.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  combined_data = combined_data.append(data, ignore_index=True)
/var/folders/b1/b6tfvntn1k3cvt9kyzby94gm0000gn/T/ipykernel_16756/2517942668.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  combined_data = combined_data.append(data, ignore_index=True)
/var/folders/b1/b6tfvntn1k3cvt9kyzby94gm0000gn/T/ipykernel_16756/2517942668.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  combined_data = combined_data.append(data, ignore_index=True)
/var/folders/b1/b6tfvntn1k3cvt9kyzby94gm0000gn/T/ipykernel_16756/2517942668.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  combined_data = combined_data.append(data, ignore_index=True)